/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OptionValidateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OptionValidateRequest{}

// OptionValidateRequest struct for OptionValidateRequest
type OptionValidateRequest struct {
	ValuesFromPlugin []RdOptionValue `json:"valuesFromPlugin,omitempty"`
	OptionValues []string `json:"optionValues,omitempty"`
	ConfigMap map[string]map[string]interface{} `json:"configMap,omitempty"`
	Errors *Errors `json:"errors,omitempty"`
	Name *string `json:"name,omitempty"`
	SortIndex *int32 `json:"sortIndex,omitempty"`
	Description *string `json:"description,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
	DefaultStoragePath *string `json:"defaultStoragePath,omitempty"`
	Enforced *bool `json:"enforced,omitempty"`
	Required *bool `json:"required,omitempty"`
	IsDate *bool `json:"isDate,omitempty"`
	DateFormat *string `json:"dateFormat,omitempty"`
	Label *string `json:"label,omitempty"`
	RealValuesUrl *string `json:"realValuesUrl,omitempty"`
	Regex *string `json:"regex,omitempty"`
	ValuesList *string `json:"valuesList,omitempty"`
	ValuesListDelimiter *string `json:"valuesListDelimiter,omitempty"`
	Multivalued *bool `json:"multivalued,omitempty"`
	Delimiter *string `json:"delimiter,omitempty"`
	SecureInput *bool `json:"secureInput,omitempty"`
	SecureExposed *bool `json:"secureExposed,omitempty"`
	OptionType *string `json:"optionType,omitempty"`
	MultivalueAllSelected *bool `json:"multivalueAllSelected,omitempty"`
	OptionValuesPluginType *string `json:"optionValuesPluginType,omitempty"`
	Hidden *bool `json:"hidden,omitempty"`
	SortValues *bool `json:"sortValues,omitempty"`
	Type *string `json:"type,omitempty"`
	StoragePath *string `json:"storagePath,omitempty"`
	ValuesUrl *string `json:"valuesUrl,omitempty"`
	Value *string `json:"value,omitempty"`
	Values []string `json:"values,omitempty"`
	Secure *bool `json:"secure,omitempty"`
	ValueExposed *bool `json:"valueExposed,omitempty"`
	ValuesType *string `json:"valuesType,omitempty"`
	RemoteUrlAuthenticationType *string `json:"remoteUrlAuthenticationType,omitempty"`
	ConfigRemoteUrl map[string]map[string]interface{} `json:"configRemoteUrl,omitempty"`
}

// NewOptionValidateRequest instantiates a new OptionValidateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOptionValidateRequest() *OptionValidateRequest {
	this := OptionValidateRequest{}
	return &this
}

// NewOptionValidateRequestWithDefaults instantiates a new OptionValidateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionValidateRequestWithDefaults() *OptionValidateRequest {
	this := OptionValidateRequest{}
	return &this
}

// GetValuesFromPlugin returns the ValuesFromPlugin field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValuesFromPlugin() []RdOptionValue {
	if o == nil || IsNil(o.ValuesFromPlugin) {
		var ret []RdOptionValue
		return ret
	}
	return o.ValuesFromPlugin
}

// GetValuesFromPluginOk returns a tuple with the ValuesFromPlugin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValuesFromPluginOk() ([]RdOptionValue, bool) {
	if o == nil || IsNil(o.ValuesFromPlugin) {
		return nil, false
	}
	return o.ValuesFromPlugin, true
}

// HasValuesFromPlugin returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValuesFromPlugin() bool {
	if o != nil && !IsNil(o.ValuesFromPlugin) {
		return true
	}

	return false
}

// SetValuesFromPlugin gets a reference to the given []RdOptionValue and assigns it to the ValuesFromPlugin field.
func (o *OptionValidateRequest) SetValuesFromPlugin(v []RdOptionValue) {
	o.ValuesFromPlugin = v
}

// GetOptionValues returns the OptionValues field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetOptionValues() []string {
	if o == nil || IsNil(o.OptionValues) {
		var ret []string
		return ret
	}
	return o.OptionValues
}

// GetOptionValuesOk returns a tuple with the OptionValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetOptionValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.OptionValues) {
		return nil, false
	}
	return o.OptionValues, true
}

// HasOptionValues returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasOptionValues() bool {
	if o != nil && !IsNil(o.OptionValues) {
		return true
	}

	return false
}

// SetOptionValues gets a reference to the given []string and assigns it to the OptionValues field.
func (o *OptionValidateRequest) SetOptionValues(v []string) {
	o.OptionValues = v
}

// GetConfigMap returns the ConfigMap field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetConfigMap() map[string]map[string]interface{} {
	if o == nil || IsNil(o.ConfigMap) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.ConfigMap
}

// GetConfigMapOk returns a tuple with the ConfigMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetConfigMapOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ConfigMap) {
		return map[string]map[string]interface{}{}, false
	}
	return o.ConfigMap, true
}

// HasConfigMap returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasConfigMap() bool {
	if o != nil && !IsNil(o.ConfigMap) {
		return true
	}

	return false
}

// SetConfigMap gets a reference to the given map[string]map[string]interface{} and assigns it to the ConfigMap field.
func (o *OptionValidateRequest) SetConfigMap(v map[string]map[string]interface{}) {
	o.ConfigMap = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetErrors() Errors {
	if o == nil || IsNil(o.Errors) {
		var ret Errors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetErrorsOk() (*Errors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given Errors and assigns it to the Errors field.
func (o *OptionValidateRequest) SetErrors(v Errors) {
	o.Errors = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OptionValidateRequest) SetName(v string) {
	o.Name = &v
}

// GetSortIndex returns the SortIndex field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetSortIndex() int32 {
	if o == nil || IsNil(o.SortIndex) {
		var ret int32
		return ret
	}
	return *o.SortIndex
}

// GetSortIndexOk returns a tuple with the SortIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetSortIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.SortIndex) {
		return nil, false
	}
	return o.SortIndex, true
}

// HasSortIndex returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasSortIndex() bool {
	if o != nil && !IsNil(o.SortIndex) {
		return true
	}

	return false
}

// SetSortIndex gets a reference to the given int32 and assigns it to the SortIndex field.
func (o *OptionValidateRequest) SetSortIndex(v int32) {
	o.SortIndex = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OptionValidateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue) {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetDefaultValueOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *OptionValidateRequest) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetDefaultStoragePath returns the DefaultStoragePath field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetDefaultStoragePath() string {
	if o == nil || IsNil(o.DefaultStoragePath) {
		var ret string
		return ret
	}
	return *o.DefaultStoragePath
}

// GetDefaultStoragePathOk returns a tuple with the DefaultStoragePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetDefaultStoragePathOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultStoragePath) {
		return nil, false
	}
	return o.DefaultStoragePath, true
}

// HasDefaultStoragePath returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasDefaultStoragePath() bool {
	if o != nil && !IsNil(o.DefaultStoragePath) {
		return true
	}

	return false
}

// SetDefaultStoragePath gets a reference to the given string and assigns it to the DefaultStoragePath field.
func (o *OptionValidateRequest) SetDefaultStoragePath(v string) {
	o.DefaultStoragePath = &v
}

// GetEnforced returns the Enforced field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetEnforced() bool {
	if o == nil || IsNil(o.Enforced) {
		var ret bool
		return ret
	}
	return *o.Enforced
}

// GetEnforcedOk returns a tuple with the Enforced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetEnforcedOk() (*bool, bool) {
	if o == nil || IsNil(o.Enforced) {
		return nil, false
	}
	return o.Enforced, true
}

// HasEnforced returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasEnforced() bool {
	if o != nil && !IsNil(o.Enforced) {
		return true
	}

	return false
}

// SetEnforced gets a reference to the given bool and assigns it to the Enforced field.
func (o *OptionValidateRequest) SetEnforced(v bool) {
	o.Enforced = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *OptionValidateRequest) SetRequired(v bool) {
	o.Required = &v
}

// GetIsDate returns the IsDate field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetIsDate() bool {
	if o == nil || IsNil(o.IsDate) {
		var ret bool
		return ret
	}
	return *o.IsDate
}

// GetIsDateOk returns a tuple with the IsDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetIsDateOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDate) {
		return nil, false
	}
	return o.IsDate, true
}

// HasIsDate returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasIsDate() bool {
	if o != nil && !IsNil(o.IsDate) {
		return true
	}

	return false
}

// SetIsDate gets a reference to the given bool and assigns it to the IsDate field.
func (o *OptionValidateRequest) SetIsDate(v bool) {
	o.IsDate = &v
}

// GetDateFormat returns the DateFormat field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetDateFormat() string {
	if o == nil || IsNil(o.DateFormat) {
		var ret string
		return ret
	}
	return *o.DateFormat
}

// GetDateFormatOk returns a tuple with the DateFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetDateFormatOk() (*string, bool) {
	if o == nil || IsNil(o.DateFormat) {
		return nil, false
	}
	return o.DateFormat, true
}

// HasDateFormat returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasDateFormat() bool {
	if o != nil && !IsNil(o.DateFormat) {
		return true
	}

	return false
}

// SetDateFormat gets a reference to the given string and assigns it to the DateFormat field.
func (o *OptionValidateRequest) SetDateFormat(v string) {
	o.DateFormat = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *OptionValidateRequest) SetLabel(v string) {
	o.Label = &v
}

// GetRealValuesUrl returns the RealValuesUrl field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetRealValuesUrl() string {
	if o == nil || IsNil(o.RealValuesUrl) {
		var ret string
		return ret
	}
	return *o.RealValuesUrl
}

// GetRealValuesUrlOk returns a tuple with the RealValuesUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetRealValuesUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RealValuesUrl) {
		return nil, false
	}
	return o.RealValuesUrl, true
}

// HasRealValuesUrl returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasRealValuesUrl() bool {
	if o != nil && !IsNil(o.RealValuesUrl) {
		return true
	}

	return false
}

// SetRealValuesUrl gets a reference to the given string and assigns it to the RealValuesUrl field.
func (o *OptionValidateRequest) SetRealValuesUrl(v string) {
	o.RealValuesUrl = &v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetRegex() string {
	if o == nil || IsNil(o.Regex) {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetRegexOk() (*string, bool) {
	if o == nil || IsNil(o.Regex) {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasRegex() bool {
	if o != nil && !IsNil(o.Regex) {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *OptionValidateRequest) SetRegex(v string) {
	o.Regex = &v
}

// GetValuesList returns the ValuesList field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValuesList() string {
	if o == nil || IsNil(o.ValuesList) {
		var ret string
		return ret
	}
	return *o.ValuesList
}

// GetValuesListOk returns a tuple with the ValuesList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValuesListOk() (*string, bool) {
	if o == nil || IsNil(o.ValuesList) {
		return nil, false
	}
	return o.ValuesList, true
}

// HasValuesList returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValuesList() bool {
	if o != nil && !IsNil(o.ValuesList) {
		return true
	}

	return false
}

// SetValuesList gets a reference to the given string and assigns it to the ValuesList field.
func (o *OptionValidateRequest) SetValuesList(v string) {
	o.ValuesList = &v
}

// GetValuesListDelimiter returns the ValuesListDelimiter field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValuesListDelimiter() string {
	if o == nil || IsNil(o.ValuesListDelimiter) {
		var ret string
		return ret
	}
	return *o.ValuesListDelimiter
}

// GetValuesListDelimiterOk returns a tuple with the ValuesListDelimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValuesListDelimiterOk() (*string, bool) {
	if o == nil || IsNil(o.ValuesListDelimiter) {
		return nil, false
	}
	return o.ValuesListDelimiter, true
}

// HasValuesListDelimiter returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValuesListDelimiter() bool {
	if o != nil && !IsNil(o.ValuesListDelimiter) {
		return true
	}

	return false
}

// SetValuesListDelimiter gets a reference to the given string and assigns it to the ValuesListDelimiter field.
func (o *OptionValidateRequest) SetValuesListDelimiter(v string) {
	o.ValuesListDelimiter = &v
}

// GetMultivalued returns the Multivalued field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetMultivalued() bool {
	if o == nil || IsNil(o.Multivalued) {
		var ret bool
		return ret
	}
	return *o.Multivalued
}

// GetMultivaluedOk returns a tuple with the Multivalued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetMultivaluedOk() (*bool, bool) {
	if o == nil || IsNil(o.Multivalued) {
		return nil, false
	}
	return o.Multivalued, true
}

// HasMultivalued returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasMultivalued() bool {
	if o != nil && !IsNil(o.Multivalued) {
		return true
	}

	return false
}

// SetMultivalued gets a reference to the given bool and assigns it to the Multivalued field.
func (o *OptionValidateRequest) SetMultivalued(v bool) {
	o.Multivalued = &v
}

// GetDelimiter returns the Delimiter field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetDelimiter() string {
	if o == nil || IsNil(o.Delimiter) {
		var ret string
		return ret
	}
	return *o.Delimiter
}

// GetDelimiterOk returns a tuple with the Delimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetDelimiterOk() (*string, bool) {
	if o == nil || IsNil(o.Delimiter) {
		return nil, false
	}
	return o.Delimiter, true
}

// HasDelimiter returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasDelimiter() bool {
	if o != nil && !IsNil(o.Delimiter) {
		return true
	}

	return false
}

// SetDelimiter gets a reference to the given string and assigns it to the Delimiter field.
func (o *OptionValidateRequest) SetDelimiter(v string) {
	o.Delimiter = &v
}

// GetSecureInput returns the SecureInput field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetSecureInput() bool {
	if o == nil || IsNil(o.SecureInput) {
		var ret bool
		return ret
	}
	return *o.SecureInput
}

// GetSecureInputOk returns a tuple with the SecureInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetSecureInputOk() (*bool, bool) {
	if o == nil || IsNil(o.SecureInput) {
		return nil, false
	}
	return o.SecureInput, true
}

// HasSecureInput returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasSecureInput() bool {
	if o != nil && !IsNil(o.SecureInput) {
		return true
	}

	return false
}

// SetSecureInput gets a reference to the given bool and assigns it to the SecureInput field.
func (o *OptionValidateRequest) SetSecureInput(v bool) {
	o.SecureInput = &v
}

// GetSecureExposed returns the SecureExposed field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetSecureExposed() bool {
	if o == nil || IsNil(o.SecureExposed) {
		var ret bool
		return ret
	}
	return *o.SecureExposed
}

// GetSecureExposedOk returns a tuple with the SecureExposed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetSecureExposedOk() (*bool, bool) {
	if o == nil || IsNil(o.SecureExposed) {
		return nil, false
	}
	return o.SecureExposed, true
}

// HasSecureExposed returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasSecureExposed() bool {
	if o != nil && !IsNil(o.SecureExposed) {
		return true
	}

	return false
}

// SetSecureExposed gets a reference to the given bool and assigns it to the SecureExposed field.
func (o *OptionValidateRequest) SetSecureExposed(v bool) {
	o.SecureExposed = &v
}

// GetOptionType returns the OptionType field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetOptionType() string {
	if o == nil || IsNil(o.OptionType) {
		var ret string
		return ret
	}
	return *o.OptionType
}

// GetOptionTypeOk returns a tuple with the OptionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetOptionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OptionType) {
		return nil, false
	}
	return o.OptionType, true
}

// HasOptionType returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasOptionType() bool {
	if o != nil && !IsNil(o.OptionType) {
		return true
	}

	return false
}

// SetOptionType gets a reference to the given string and assigns it to the OptionType field.
func (o *OptionValidateRequest) SetOptionType(v string) {
	o.OptionType = &v
}

// GetMultivalueAllSelected returns the MultivalueAllSelected field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetMultivalueAllSelected() bool {
	if o == nil || IsNil(o.MultivalueAllSelected) {
		var ret bool
		return ret
	}
	return *o.MultivalueAllSelected
}

// GetMultivalueAllSelectedOk returns a tuple with the MultivalueAllSelected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetMultivalueAllSelectedOk() (*bool, bool) {
	if o == nil || IsNil(o.MultivalueAllSelected) {
		return nil, false
	}
	return o.MultivalueAllSelected, true
}

// HasMultivalueAllSelected returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasMultivalueAllSelected() bool {
	if o != nil && !IsNil(o.MultivalueAllSelected) {
		return true
	}

	return false
}

// SetMultivalueAllSelected gets a reference to the given bool and assigns it to the MultivalueAllSelected field.
func (o *OptionValidateRequest) SetMultivalueAllSelected(v bool) {
	o.MultivalueAllSelected = &v
}

// GetOptionValuesPluginType returns the OptionValuesPluginType field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetOptionValuesPluginType() string {
	if o == nil || IsNil(o.OptionValuesPluginType) {
		var ret string
		return ret
	}
	return *o.OptionValuesPluginType
}

// GetOptionValuesPluginTypeOk returns a tuple with the OptionValuesPluginType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetOptionValuesPluginTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OptionValuesPluginType) {
		return nil, false
	}
	return o.OptionValuesPluginType, true
}

// HasOptionValuesPluginType returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasOptionValuesPluginType() bool {
	if o != nil && !IsNil(o.OptionValuesPluginType) {
		return true
	}

	return false
}

// SetOptionValuesPluginType gets a reference to the given string and assigns it to the OptionValuesPluginType field.
func (o *OptionValidateRequest) SetOptionValuesPluginType(v string) {
	o.OptionValuesPluginType = &v
}

// GetHidden returns the Hidden field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetHidden() bool {
	if o == nil || IsNil(o.Hidden) {
		var ret bool
		return ret
	}
	return *o.Hidden
}

// GetHiddenOk returns a tuple with the Hidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.Hidden) {
		return nil, false
	}
	return o.Hidden, true
}

// HasHidden returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasHidden() bool {
	if o != nil && !IsNil(o.Hidden) {
		return true
	}

	return false
}

// SetHidden gets a reference to the given bool and assigns it to the Hidden field.
func (o *OptionValidateRequest) SetHidden(v bool) {
	o.Hidden = &v
}

// GetSortValues returns the SortValues field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetSortValues() bool {
	if o == nil || IsNil(o.SortValues) {
		var ret bool
		return ret
	}
	return *o.SortValues
}

// GetSortValuesOk returns a tuple with the SortValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetSortValuesOk() (*bool, bool) {
	if o == nil || IsNil(o.SortValues) {
		return nil, false
	}
	return o.SortValues, true
}

// HasSortValues returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasSortValues() bool {
	if o != nil && !IsNil(o.SortValues) {
		return true
	}

	return false
}

// SetSortValues gets a reference to the given bool and assigns it to the SortValues field.
func (o *OptionValidateRequest) SetSortValues(v bool) {
	o.SortValues = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OptionValidateRequest) SetType(v string) {
	o.Type = &v
}

// GetStoragePath returns the StoragePath field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetStoragePath() string {
	if o == nil || IsNil(o.StoragePath) {
		var ret string
		return ret
	}
	return *o.StoragePath
}

// GetStoragePathOk returns a tuple with the StoragePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetStoragePathOk() (*string, bool) {
	if o == nil || IsNil(o.StoragePath) {
		return nil, false
	}
	return o.StoragePath, true
}

// HasStoragePath returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasStoragePath() bool {
	if o != nil && !IsNil(o.StoragePath) {
		return true
	}

	return false
}

// SetStoragePath gets a reference to the given string and assigns it to the StoragePath field.
func (o *OptionValidateRequest) SetStoragePath(v string) {
	o.StoragePath = &v
}

// GetValuesUrl returns the ValuesUrl field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValuesUrl() string {
	if o == nil || IsNil(o.ValuesUrl) {
		var ret string
		return ret
	}
	return *o.ValuesUrl
}

// GetValuesUrlOk returns a tuple with the ValuesUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValuesUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ValuesUrl) {
		return nil, false
	}
	return o.ValuesUrl, true
}

// HasValuesUrl returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValuesUrl() bool {
	if o != nil && !IsNil(o.ValuesUrl) {
		return true
	}

	return false
}

// SetValuesUrl gets a reference to the given string and assigns it to the ValuesUrl field.
func (o *OptionValidateRequest) SetValuesUrl(v string) {
	o.ValuesUrl = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *OptionValidateRequest) SetValue(v string) {
	o.Value = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *OptionValidateRequest) SetValues(v []string) {
	o.Values = v
}

// GetSecure returns the Secure field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetSecure() bool {
	if o == nil || IsNil(o.Secure) {
		var ret bool
		return ret
	}
	return *o.Secure
}

// GetSecureOk returns a tuple with the Secure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetSecureOk() (*bool, bool) {
	if o == nil || IsNil(o.Secure) {
		return nil, false
	}
	return o.Secure, true
}

// HasSecure returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasSecure() bool {
	if o != nil && !IsNil(o.Secure) {
		return true
	}

	return false
}

// SetSecure gets a reference to the given bool and assigns it to the Secure field.
func (o *OptionValidateRequest) SetSecure(v bool) {
	o.Secure = &v
}

// GetValueExposed returns the ValueExposed field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValueExposed() bool {
	if o == nil || IsNil(o.ValueExposed) {
		var ret bool
		return ret
	}
	return *o.ValueExposed
}

// GetValueExposedOk returns a tuple with the ValueExposed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValueExposedOk() (*bool, bool) {
	if o == nil || IsNil(o.ValueExposed) {
		return nil, false
	}
	return o.ValueExposed, true
}

// HasValueExposed returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValueExposed() bool {
	if o != nil && !IsNil(o.ValueExposed) {
		return true
	}

	return false
}

// SetValueExposed gets a reference to the given bool and assigns it to the ValueExposed field.
func (o *OptionValidateRequest) SetValueExposed(v bool) {
	o.ValueExposed = &v
}

// GetValuesType returns the ValuesType field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetValuesType() string {
	if o == nil || IsNil(o.ValuesType) {
		var ret string
		return ret
	}
	return *o.ValuesType
}

// GetValuesTypeOk returns a tuple with the ValuesType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetValuesTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ValuesType) {
		return nil, false
	}
	return o.ValuesType, true
}

// HasValuesType returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasValuesType() bool {
	if o != nil && !IsNil(o.ValuesType) {
		return true
	}

	return false
}

// SetValuesType gets a reference to the given string and assigns it to the ValuesType field.
func (o *OptionValidateRequest) SetValuesType(v string) {
	o.ValuesType = &v
}

// GetRemoteUrlAuthenticationType returns the RemoteUrlAuthenticationType field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetRemoteUrlAuthenticationType() string {
	if o == nil || IsNil(o.RemoteUrlAuthenticationType) {
		var ret string
		return ret
	}
	return *o.RemoteUrlAuthenticationType
}

// GetRemoteUrlAuthenticationTypeOk returns a tuple with the RemoteUrlAuthenticationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetRemoteUrlAuthenticationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteUrlAuthenticationType) {
		return nil, false
	}
	return o.RemoteUrlAuthenticationType, true
}

// HasRemoteUrlAuthenticationType returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasRemoteUrlAuthenticationType() bool {
	if o != nil && !IsNil(o.RemoteUrlAuthenticationType) {
		return true
	}

	return false
}

// SetRemoteUrlAuthenticationType gets a reference to the given string and assigns it to the RemoteUrlAuthenticationType field.
func (o *OptionValidateRequest) SetRemoteUrlAuthenticationType(v string) {
	o.RemoteUrlAuthenticationType = &v
}

// GetConfigRemoteUrl returns the ConfigRemoteUrl field value if set, zero value otherwise.
func (o *OptionValidateRequest) GetConfigRemoteUrl() map[string]map[string]interface{} {
	if o == nil || IsNil(o.ConfigRemoteUrl) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.ConfigRemoteUrl
}

// GetConfigRemoteUrlOk returns a tuple with the ConfigRemoteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionValidateRequest) GetConfigRemoteUrlOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ConfigRemoteUrl) {
		return map[string]map[string]interface{}{}, false
	}
	return o.ConfigRemoteUrl, true
}

// HasConfigRemoteUrl returns a boolean if a field has been set.
func (o *OptionValidateRequest) HasConfigRemoteUrl() bool {
	if o != nil && !IsNil(o.ConfigRemoteUrl) {
		return true
	}

	return false
}

// SetConfigRemoteUrl gets a reference to the given map[string]map[string]interface{} and assigns it to the ConfigRemoteUrl field.
func (o *OptionValidateRequest) SetConfigRemoteUrl(v map[string]map[string]interface{}) {
	o.ConfigRemoteUrl = v
}

func (o OptionValidateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OptionValidateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ValuesFromPlugin) {
		toSerialize["valuesFromPlugin"] = o.ValuesFromPlugin
	}
	if !IsNil(o.OptionValues) {
		toSerialize["optionValues"] = o.OptionValues
	}
	if !IsNil(o.ConfigMap) {
		toSerialize["configMap"] = o.ConfigMap
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SortIndex) {
		toSerialize["sortIndex"] = o.SortIndex
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.DefaultStoragePath) {
		toSerialize["defaultStoragePath"] = o.DefaultStoragePath
	}
	if !IsNil(o.Enforced) {
		toSerialize["enforced"] = o.Enforced
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.IsDate) {
		toSerialize["isDate"] = o.IsDate
	}
	if !IsNil(o.DateFormat) {
		toSerialize["dateFormat"] = o.DateFormat
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.RealValuesUrl) {
		toSerialize["realValuesUrl"] = o.RealValuesUrl
	}
	if !IsNil(o.Regex) {
		toSerialize["regex"] = o.Regex
	}
	if !IsNil(o.ValuesList) {
		toSerialize["valuesList"] = o.ValuesList
	}
	if !IsNil(o.ValuesListDelimiter) {
		toSerialize["valuesListDelimiter"] = o.ValuesListDelimiter
	}
	if !IsNil(o.Multivalued) {
		toSerialize["multivalued"] = o.Multivalued
	}
	if !IsNil(o.Delimiter) {
		toSerialize["delimiter"] = o.Delimiter
	}
	if !IsNil(o.SecureInput) {
		toSerialize["secureInput"] = o.SecureInput
	}
	if !IsNil(o.SecureExposed) {
		toSerialize["secureExposed"] = o.SecureExposed
	}
	if !IsNil(o.OptionType) {
		toSerialize["optionType"] = o.OptionType
	}
	if !IsNil(o.MultivalueAllSelected) {
		toSerialize["multivalueAllSelected"] = o.MultivalueAllSelected
	}
	if !IsNil(o.OptionValuesPluginType) {
		toSerialize["optionValuesPluginType"] = o.OptionValuesPluginType
	}
	if !IsNil(o.Hidden) {
		toSerialize["hidden"] = o.Hidden
	}
	if !IsNil(o.SortValues) {
		toSerialize["sortValues"] = o.SortValues
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.StoragePath) {
		toSerialize["storagePath"] = o.StoragePath
	}
	if !IsNil(o.ValuesUrl) {
		toSerialize["valuesUrl"] = o.ValuesUrl
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Secure) {
		toSerialize["secure"] = o.Secure
	}
	if !IsNil(o.ValueExposed) {
		toSerialize["valueExposed"] = o.ValueExposed
	}
	if !IsNil(o.ValuesType) {
		toSerialize["valuesType"] = o.ValuesType
	}
	if !IsNil(o.RemoteUrlAuthenticationType) {
		toSerialize["remoteUrlAuthenticationType"] = o.RemoteUrlAuthenticationType
	}
	if !IsNil(o.ConfigRemoteUrl) {
		toSerialize["configRemoteUrl"] = o.ConfigRemoteUrl
	}
	return toSerialize, nil
}

type NullableOptionValidateRequest struct {
	value *OptionValidateRequest
	isSet bool
}

func (v NullableOptionValidateRequest) Get() *OptionValidateRequest {
	return v.value
}

func (v *NullableOptionValidateRequest) Set(val *OptionValidateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOptionValidateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOptionValidateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptionValidateRequest(val *OptionValidateRequest) *NullableOptionValidateRequest {
	return &NullableOptionValidateRequest{value: val, isSet: true}
}

func (v NullableOptionValidateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptionValidateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


