/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KindResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindResource{}

// KindResource A resource kind
type KindResource struct {
	// Resource kind
	Kind string `json:"kind"`
}

type _KindResource KindResource

// NewKindResource instantiates a new KindResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindResource(kind string) *KindResource {
	this := KindResource{}
	this.Kind = kind
	return &this
}

// NewKindResourceWithDefaults instantiates a new KindResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindResourceWithDefaults() *KindResource {
	this := KindResource{}
	return &this
}

// GetKind returns the Kind field value
func (o *KindResource) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *KindResource) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *KindResource) SetKind(v string) {
	o.Kind = v
}

func (o KindResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	return toSerialize, nil
}

func (o *KindResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKindResource := _KindResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKindResource)

	if err != nil {
		return err
	}

	*o = KindResource(varKindResource)

	return err
}

type NullableKindResource struct {
	value *KindResource
	isSet bool
}

func (v NullableKindResource) Get() *KindResource {
	return v.value
}

func (v *NullableKindResource) Set(val *KindResource) {
	v.value = val
	v.isSet = true
}

func (v NullableKindResource) IsSet() bool {
	return v.isSet
}

func (v *NullableKindResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindResource(val *KindResource) *NullableKindResource {
	return &NullableKindResource{value: val, isSet: true}
}

func (v NullableKindResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


