/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectExecutionModeLaterCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectExecutionModeLaterCommand{}

// ProjectExecutionModeLaterCommand struct for ProjectExecutionModeLaterCommand
type ProjectExecutionModeLaterCommand struct {
	Type *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewProjectExecutionModeLaterCommand instantiates a new ProjectExecutionModeLaterCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectExecutionModeLaterCommand() *ProjectExecutionModeLaterCommand {
	this := ProjectExecutionModeLaterCommand{}
	return &this
}

// NewProjectExecutionModeLaterCommandWithDefaults instantiates a new ProjectExecutionModeLaterCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectExecutionModeLaterCommandWithDefaults() *ProjectExecutionModeLaterCommand {
	this := ProjectExecutionModeLaterCommand{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ProjectExecutionModeLaterCommand) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectExecutionModeLaterCommand) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ProjectExecutionModeLaterCommand) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ProjectExecutionModeLaterCommand) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ProjectExecutionModeLaterCommand) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectExecutionModeLaterCommand) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ProjectExecutionModeLaterCommand) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ProjectExecutionModeLaterCommand) SetValue(v string) {
	o.Value = &v
}

func (o ProjectExecutionModeLaterCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectExecutionModeLaterCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableProjectExecutionModeLaterCommand struct {
	value *ProjectExecutionModeLaterCommand
	isSet bool
}

func (v NullableProjectExecutionModeLaterCommand) Get() *ProjectExecutionModeLaterCommand {
	return v.value
}

func (v *NullableProjectExecutionModeLaterCommand) Set(val *ProjectExecutionModeLaterCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectExecutionModeLaterCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectExecutionModeLaterCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectExecutionModeLaterCommand(val *ProjectExecutionModeLaterCommand) *NullableProjectExecutionModeLaterCommand {
	return &NullableProjectExecutionModeLaterCommand{value: val, isSet: true}
}

func (v NullableProjectExecutionModeLaterCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectExecutionModeLaterCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


