/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateTokenBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTokenBase{}

// CreateTokenBase struct for CreateTokenBase
type CreateTokenBase struct {
	User *string `json:"user,omitempty"`
	// since: v19
	Duration *string `json:"duration,omitempty"`
	// since: v19
	Name *string `json:"name,omitempty"`
}

// NewCreateTokenBase instantiates a new CreateTokenBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTokenBase() *CreateTokenBase {
	this := CreateTokenBase{}
	return &this
}

// NewCreateTokenBaseWithDefaults instantiates a new CreateTokenBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTokenBaseWithDefaults() *CreateTokenBase {
	this := CreateTokenBase{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *CreateTokenBase) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTokenBase) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *CreateTokenBase) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *CreateTokenBase) SetUser(v string) {
	o.User = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *CreateTokenBase) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTokenBase) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *CreateTokenBase) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *CreateTokenBase) SetDuration(v string) {
	o.Duration = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateTokenBase) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTokenBase) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateTokenBase) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateTokenBase) SetName(v string) {
	o.Name = &v
}

func (o CreateTokenBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTokenBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateTokenBase struct {
	value *CreateTokenBase
	isSet bool
}

func (v NullableCreateTokenBase) Get() *CreateTokenBase {
	return v.value
}

func (v *NullableCreateTokenBase) Set(val *CreateTokenBase) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTokenBase) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTokenBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTokenBase(val *CreateTokenBase) *NullableCreateTokenBase {
	return &NullableCreateTokenBase{value: val, isSet: true}
}

func (v NullableCreateTokenBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTokenBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


