/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RunnerReplicaStartUp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunnerReplicaStartUp{}

// RunnerReplicaStartUp struct for RunnerReplicaStartUp
type RunnerReplicaStartUp struct {
	RunnerId *string `json:"runner-id,omitempty"`
	ReplicaId *string `json:"replica-id,omitempty"`
	InstallationPath *string `json:"installation-path,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	Osfamily *string `json:"osfamily,omitempty"`
	Ipaddress *string `json:"ipaddress,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewRunnerReplicaStartUp instantiates a new RunnerReplicaStartUp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunnerReplicaStartUp() *RunnerReplicaStartUp {
	this := RunnerReplicaStartUp{}
	return &this
}

// NewRunnerReplicaStartUpWithDefaults instantiates a new RunnerReplicaStartUp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunnerReplicaStartUpWithDefaults() *RunnerReplicaStartUp {
	this := RunnerReplicaStartUp{}
	return &this
}

// GetRunnerId returns the RunnerId field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetRunnerId() string {
	if o == nil || IsNil(o.RunnerId) {
		var ret string
		return ret
	}
	return *o.RunnerId
}

// GetRunnerIdOk returns a tuple with the RunnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetRunnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerId) {
		return nil, false
	}
	return o.RunnerId, true
}

// HasRunnerId returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasRunnerId() bool {
	if o != nil && !IsNil(o.RunnerId) {
		return true
	}

	return false
}

// SetRunnerId gets a reference to the given string and assigns it to the RunnerId field.
func (o *RunnerReplicaStartUp) SetRunnerId(v string) {
	o.RunnerId = &v
}

// GetReplicaId returns the ReplicaId field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetReplicaId() string {
	if o == nil || IsNil(o.ReplicaId) {
		var ret string
		return ret
	}
	return *o.ReplicaId
}

// GetReplicaIdOk returns a tuple with the ReplicaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetReplicaIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReplicaId) {
		return nil, false
	}
	return o.ReplicaId, true
}

// HasReplicaId returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasReplicaId() bool {
	if o != nil && !IsNil(o.ReplicaId) {
		return true
	}

	return false
}

// SetReplicaId gets a reference to the given string and assigns it to the ReplicaId field.
func (o *RunnerReplicaStartUp) SetReplicaId(v string) {
	o.ReplicaId = &v
}

// GetInstallationPath returns the InstallationPath field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetInstallationPath() string {
	if o == nil || IsNil(o.InstallationPath) {
		var ret string
		return ret
	}
	return *o.InstallationPath
}

// GetInstallationPathOk returns a tuple with the InstallationPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetInstallationPathOk() (*string, bool) {
	if o == nil || IsNil(o.InstallationPath) {
		return nil, false
	}
	return o.InstallationPath, true
}

// HasInstallationPath returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasInstallationPath() bool {
	if o != nil && !IsNil(o.InstallationPath) {
		return true
	}

	return false
}

// SetInstallationPath gets a reference to the given string and assigns it to the InstallationPath field.
func (o *RunnerReplicaStartUp) SetInstallationPath(v string) {
	o.InstallationPath = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *RunnerReplicaStartUp) SetHostname(v string) {
	o.Hostname = &v
}

// GetOsfamily returns the Osfamily field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetOsfamily() string {
	if o == nil || IsNil(o.Osfamily) {
		var ret string
		return ret
	}
	return *o.Osfamily
}

// GetOsfamilyOk returns a tuple with the Osfamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetOsfamilyOk() (*string, bool) {
	if o == nil || IsNil(o.Osfamily) {
		return nil, false
	}
	return o.Osfamily, true
}

// HasOsfamily returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasOsfamily() bool {
	if o != nil && !IsNil(o.Osfamily) {
		return true
	}

	return false
}

// SetOsfamily gets a reference to the given string and assigns it to the Osfamily field.
func (o *RunnerReplicaStartUp) SetOsfamily(v string) {
	o.Osfamily = &v
}

// GetIpaddress returns the Ipaddress field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetIpaddress() string {
	if o == nil || IsNil(o.Ipaddress) {
		var ret string
		return ret
	}
	return *o.Ipaddress
}

// GetIpaddressOk returns a tuple with the Ipaddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetIpaddressOk() (*string, bool) {
	if o == nil || IsNil(o.Ipaddress) {
		return nil, false
	}
	return o.Ipaddress, true
}

// HasIpaddress returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasIpaddress() bool {
	if o != nil && !IsNil(o.Ipaddress) {
		return true
	}

	return false
}

// SetIpaddress gets a reference to the given string and assigns it to the Ipaddress field.
func (o *RunnerReplicaStartUp) SetIpaddress(v string) {
	o.Ipaddress = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *RunnerReplicaStartUp) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerReplicaStartUp) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *RunnerReplicaStartUp) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *RunnerReplicaStartUp) SetVersion(v string) {
	o.Version = &v
}

func (o RunnerReplicaStartUp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunnerReplicaStartUp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RunnerId) {
		toSerialize["runner-id"] = o.RunnerId
	}
	if !IsNil(o.ReplicaId) {
		toSerialize["replica-id"] = o.ReplicaId
	}
	if !IsNil(o.InstallationPath) {
		toSerialize["installation-path"] = o.InstallationPath
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Osfamily) {
		toSerialize["osfamily"] = o.Osfamily
	}
	if !IsNil(o.Ipaddress) {
		toSerialize["ipaddress"] = o.Ipaddress
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableRunnerReplicaStartUp struct {
	value *RunnerReplicaStartUp
	isSet bool
}

func (v NullableRunnerReplicaStartUp) Get() *RunnerReplicaStartUp {
	return v.value
}

func (v *NullableRunnerReplicaStartUp) Set(val *RunnerReplicaStartUp) {
	v.value = val
	v.isSet = true
}

func (v NullableRunnerReplicaStartUp) IsSet() bool {
	return v.isSet
}

func (v *NullableRunnerReplicaStartUp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunnerReplicaStartUp(val *RunnerReplicaStartUp) *NullableRunnerReplicaStartUp {
	return &NullableRunnerReplicaStartUp{value: val, isSet: true}
}

func (v NullableRunnerReplicaStartUp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunnerReplicaStartUp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


