/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationAuthorizationContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationAuthorizationContext{}

// ApplicationAuthorizationContext Authorizations in the context of an application
type ApplicationAuthorizationContext struct {
	// Context type
	Type string `json:"type"`
}

type _ApplicationAuthorizationContext ApplicationAuthorizationContext

// NewApplicationAuthorizationContext instantiates a new ApplicationAuthorizationContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationAuthorizationContext(type_ string) *ApplicationAuthorizationContext {
	this := ApplicationAuthorizationContext{}
	this.Type = type_
	return &this
}

// NewApplicationAuthorizationContextWithDefaults instantiates a new ApplicationAuthorizationContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationAuthorizationContextWithDefaults() *ApplicationAuthorizationContext {
	this := ApplicationAuthorizationContext{}
	return &this
}

// GetType returns the Type field value
func (o *ApplicationAuthorizationContext) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApplicationAuthorizationContext) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApplicationAuthorizationContext) SetType(v string) {
	o.Type = v
}

func (o ApplicationAuthorizationContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationAuthorizationContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ApplicationAuthorizationContext) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationAuthorizationContext := _ApplicationAuthorizationContext{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationAuthorizationContext)

	if err != nil {
		return err
	}

	*o = ApplicationAuthorizationContext(varApplicationAuthorizationContext)

	return err
}

type NullableApplicationAuthorizationContext struct {
	value *ApplicationAuthorizationContext
	isSet bool
}

func (v NullableApplicationAuthorizationContext) Get() *ApplicationAuthorizationContext {
	return v.value
}

func (v *NullableApplicationAuthorizationContext) Set(val *ApplicationAuthorizationContext) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationAuthorizationContext) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationAuthorizationContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationAuthorizationContext(val *ApplicationAuthorizationContext) *NullableApplicationAuthorizationContext {
	return &NullableApplicationAuthorizationContext{value: val, isSet: true}
}

func (v NullableApplicationAuthorizationContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationAuthorizationContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


