/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScmToggleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScmToggleRequest{}

// ScmToggleRequest struct for ScmToggleRequest
type ScmToggleRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewScmToggleRequest instantiates a new ScmToggleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScmToggleRequest() *ScmToggleRequest {
	this := ScmToggleRequest{}
	return &this
}

// NewScmToggleRequestWithDefaults instantiates a new ScmToggleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScmToggleRequestWithDefaults() *ScmToggleRequest {
	this := ScmToggleRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ScmToggleRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScmToggleRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ScmToggleRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ScmToggleRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o ScmToggleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScmToggleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableScmToggleRequest struct {
	value *ScmToggleRequest
	isSet bool
}

func (v NullableScmToggleRequest) Get() *ScmToggleRequest {
	return v.value
}

func (v *NullableScmToggleRequest) Set(val *ScmToggleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScmToggleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScmToggleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScmToggleRequest(val *ScmToggleRequest) *NullableScmToggleRequest {
	return &NullableScmToggleRequest{value: val, isSet: true}
}

func (v NullableScmToggleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScmToggleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


