/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AuthorizationsResponseResource - struct for AuthorizationsResponseResource
type AuthorizationsResponseResource struct {
	KindResource *KindResource
	TypeResource *TypeResource
}

// KindResourceAsAuthorizationsResponseResource is a convenience function that returns KindResource wrapped in AuthorizationsResponseResource
func KindResourceAsAuthorizationsResponseResource(v *KindResource) AuthorizationsResponseResource {
	return AuthorizationsResponseResource{
		KindResource: v,
	}
}

// TypeResourceAsAuthorizationsResponseResource is a convenience function that returns TypeResource wrapped in AuthorizationsResponseResource
func TypeResourceAsAuthorizationsResponseResource(v *TypeResource) AuthorizationsResponseResource {
	return AuthorizationsResponseResource{
		TypeResource: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AuthorizationsResponseResource) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into KindResource
	err = newStrictDecoder(data).Decode(&dst.KindResource)
	if err == nil {
		jsonKindResource, _ := json.Marshal(dst.KindResource)
		if string(jsonKindResource) == "{}" { // empty struct
			dst.KindResource = nil
		} else {
			if err = validator.Validate(dst.KindResource); err != nil {
				dst.KindResource = nil
			} else {
				match++
			}
		}
	} else {
		dst.KindResource = nil
	}

	// try to unmarshal data into TypeResource
	err = newStrictDecoder(data).Decode(&dst.TypeResource)
	if err == nil {
		jsonTypeResource, _ := json.Marshal(dst.TypeResource)
		if string(jsonTypeResource) == "{}" { // empty struct
			dst.TypeResource = nil
		} else {
			if err = validator.Validate(dst.TypeResource); err != nil {
				dst.TypeResource = nil
			} else {
				match++
			}
		}
	} else {
		dst.TypeResource = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.KindResource = nil
		dst.TypeResource = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AuthorizationsResponseResource)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(AuthorizationsResponseResource): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(AuthorizationsResponseResource)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AuthorizationsResponseResource) MarshalJSON() ([]byte, error) {
	if src.KindResource != nil {
		return json.Marshal(&src.KindResource)
	}

	if src.TypeResource != nil {
		return json.Marshal(&src.TypeResource)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AuthorizationsResponseResource) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.KindResource != nil {
		return obj.KindResource
	}

	if obj.TypeResource != nil {
		return obj.TypeResource
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AuthorizationsResponseResource) GetActualInstanceValue() (interface{}) {
	if obj.KindResource != nil {
		return *obj.KindResource
	}

	if obj.TypeResource != nil {
		return *obj.TypeResource
	}

	// all schemas are nil
	return nil
}

type NullableAuthorizationsResponseResource struct {
	value *AuthorizationsResponseResource
	isSet bool
}

func (v NullableAuthorizationsResponseResource) Get() *AuthorizationsResponseResource {
	return v.value
}

func (v *NullableAuthorizationsResponseResource) Set(val *AuthorizationsResponseResource) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationsResponseResource) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationsResponseResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationsResponseResource(val *AuthorizationsResponseResource) *NullableAuthorizationsResponseResource {
	return &NullableAuthorizationsResponseResource{value: val, isSet: true}
}

func (v NullableAuthorizationsResponseResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationsResponseResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


