/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectAuthorizationContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAuthorizationContext{}

// ProjectAuthorizationContext Authorizations in the context of a project
type ProjectAuthorizationContext struct {
	// Context type
	Type string `json:"type"`
	// Context name
	Name string `json:"name"`
}

type _ProjectAuthorizationContext ProjectAuthorizationContext

// NewProjectAuthorizationContext instantiates a new ProjectAuthorizationContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAuthorizationContext(type_ string, name string) *ProjectAuthorizationContext {
	this := ProjectAuthorizationContext{}
	this.Type = type_
	this.Name = name
	return &this
}

// NewProjectAuthorizationContextWithDefaults instantiates a new ProjectAuthorizationContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAuthorizationContextWithDefaults() *ProjectAuthorizationContext {
	this := ProjectAuthorizationContext{}
	return &this
}

// GetType returns the Type field value
func (o *ProjectAuthorizationContext) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProjectAuthorizationContext) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProjectAuthorizationContext) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *ProjectAuthorizationContext) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectAuthorizationContext) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectAuthorizationContext) SetName(v string) {
	o.Name = v
}

func (o ProjectAuthorizationContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAuthorizationContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ProjectAuthorizationContext) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectAuthorizationContext := _ProjectAuthorizationContext{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectAuthorizationContext)

	if err != nil {
		return err
	}

	*o = ProjectAuthorizationContext(varProjectAuthorizationContext)

	return err
}

type NullableProjectAuthorizationContext struct {
	value *ProjectAuthorizationContext
	isSet bool
}

func (v NullableProjectAuthorizationContext) Get() *ProjectAuthorizationContext {
	return v.value
}

func (v *NullableProjectAuthorizationContext) Set(val *ProjectAuthorizationContext) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAuthorizationContext) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAuthorizationContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAuthorizationContext(val *ProjectAuthorizationContext) *NullableProjectAuthorizationContext {
	return &NullableProjectAuthorizationContext{value: val, isSet: true}
}

func (v NullableProjectAuthorizationContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAuthorizationContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


