/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiBulkJobDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiBulkJobDeleteRequest{}

// ApiBulkJobDeleteRequest struct for ApiBulkJobDeleteRequest
type ApiBulkJobDeleteRequest struct {
	Ids []string `json:"ids,omitempty"`
	Idlist *string `json:"idlist,omitempty"`
	Id *string `json:"id,omitempty"`
	Errors *Errors `json:"errors,omitempty"`
}

// NewApiBulkJobDeleteRequest instantiates a new ApiBulkJobDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiBulkJobDeleteRequest() *ApiBulkJobDeleteRequest {
	this := ApiBulkJobDeleteRequest{}
	return &this
}

// NewApiBulkJobDeleteRequestWithDefaults instantiates a new ApiBulkJobDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiBulkJobDeleteRequestWithDefaults() *ApiBulkJobDeleteRequest {
	this := ApiBulkJobDeleteRequest{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *ApiBulkJobDeleteRequest) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBulkJobDeleteRequest) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *ApiBulkJobDeleteRequest) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *ApiBulkJobDeleteRequest) SetIds(v []string) {
	o.Ids = v
}

// GetIdlist returns the Idlist field value if set, zero value otherwise.
func (o *ApiBulkJobDeleteRequest) GetIdlist() string {
	if o == nil || IsNil(o.Idlist) {
		var ret string
		return ret
	}
	return *o.Idlist
}

// GetIdlistOk returns a tuple with the Idlist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBulkJobDeleteRequest) GetIdlistOk() (*string, bool) {
	if o == nil || IsNil(o.Idlist) {
		return nil, false
	}
	return o.Idlist, true
}

// HasIdlist returns a boolean if a field has been set.
func (o *ApiBulkJobDeleteRequest) HasIdlist() bool {
	if o != nil && !IsNil(o.Idlist) {
		return true
	}

	return false
}

// SetIdlist gets a reference to the given string and assigns it to the Idlist field.
func (o *ApiBulkJobDeleteRequest) SetIdlist(v string) {
	o.Idlist = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiBulkJobDeleteRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBulkJobDeleteRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiBulkJobDeleteRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiBulkJobDeleteRequest) SetId(v string) {
	o.Id = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ApiBulkJobDeleteRequest) GetErrors() Errors {
	if o == nil || IsNil(o.Errors) {
		var ret Errors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBulkJobDeleteRequest) GetErrorsOk() (*Errors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ApiBulkJobDeleteRequest) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given Errors and assigns it to the Errors field.
func (o *ApiBulkJobDeleteRequest) SetErrors(v Errors) {
	o.Errors = &v
}

func (o ApiBulkJobDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiBulkJobDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.Idlist) {
		toSerialize["idlist"] = o.Idlist
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableApiBulkJobDeleteRequest struct {
	value *ApiBulkJobDeleteRequest
	isSet bool
}

func (v NullableApiBulkJobDeleteRequest) Get() *ApiBulkJobDeleteRequest {
	return v.value
}

func (v *NullableApiBulkJobDeleteRequest) Set(val *ApiBulkJobDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiBulkJobDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiBulkJobDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiBulkJobDeleteRequest(val *ApiBulkJobDeleteRequest) *NullableApiBulkJobDeleteRequest {
	return &NullableApiBulkJobDeleteRequest{value: val, isSet: true}
}

func (v NullableApiBulkJobDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiBulkJobDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


