/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SystemInfoModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemInfoModel{}

// SystemInfoModel System Information
type SystemInfoModel struct {
	// System Information
	System *SystemInfoModelSystemInfoSystem `json:"system,omitempty"`
}

// NewSystemInfoModel instantiates a new SystemInfoModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInfoModel() *SystemInfoModel {
	this := SystemInfoModel{}
	return &this
}

// NewSystemInfoModelWithDefaults instantiates a new SystemInfoModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInfoModelWithDefaults() *SystemInfoModel {
	this := SystemInfoModel{}
	return &this
}

// GetSystem returns the System field value if set, zero value otherwise.
func (o *SystemInfoModel) GetSystem() SystemInfoModelSystemInfoSystem {
	if o == nil || IsNil(o.System) {
		var ret SystemInfoModelSystemInfoSystem
		return ret
	}
	return *o.System
}

// GetSystemOk returns a tuple with the System field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModel) GetSystemOk() (*SystemInfoModelSystemInfoSystem, bool) {
	if o == nil || IsNil(o.System) {
		return nil, false
	}
	return o.System, true
}

// HasSystem returns a boolean if a field has been set.
func (o *SystemInfoModel) HasSystem() bool {
	if o != nil && !IsNil(o.System) {
		return true
	}

	return false
}

// SetSystem gets a reference to the given SystemInfoModelSystemInfoSystem and assigns it to the System field.
func (o *SystemInfoModel) SetSystem(v SystemInfoModelSystemInfoSystem) {
	o.System = &v
}

func (o SystemInfoModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemInfoModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.System) {
		toSerialize["system"] = o.System
	}
	return toSerialize, nil
}

type NullableSystemInfoModel struct {
	value *SystemInfoModel
	isSet bool
}

func (v NullableSystemInfoModel) Get() *SystemInfoModel {
	return v.value
}

func (v *NullableSystemInfoModel) Set(val *SystemInfoModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInfoModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInfoModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInfoModel(val *SystemInfoModel) *NullableSystemInfoModel {
	return &NullableSystemInfoModel{value: val, isSet: true}
}

func (v NullableSystemInfoModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInfoModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


