/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefaultMessageSourceResolvable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultMessageSourceResolvable{}

// DefaultMessageSourceResolvable struct for DefaultMessageSourceResolvable
type DefaultMessageSourceResolvable struct {
	Code string `json:"code"`
	Codes []string `json:"codes,omitempty"`
	Arguments []map[string]interface{} `json:"arguments,omitempty"`
	DefaultMessage *string `json:"defaultMessage,omitempty"`
}

type _DefaultMessageSourceResolvable DefaultMessageSourceResolvable

// NewDefaultMessageSourceResolvable instantiates a new DefaultMessageSourceResolvable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultMessageSourceResolvable(code string) *DefaultMessageSourceResolvable {
	this := DefaultMessageSourceResolvable{}
	this.Code = code
	return &this
}

// NewDefaultMessageSourceResolvableWithDefaults instantiates a new DefaultMessageSourceResolvable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultMessageSourceResolvableWithDefaults() *DefaultMessageSourceResolvable {
	this := DefaultMessageSourceResolvable{}
	return &this
}

// GetCode returns the Code field value
func (o *DefaultMessageSourceResolvable) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DefaultMessageSourceResolvable) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DefaultMessageSourceResolvable) SetCode(v string) {
	o.Code = v
}

// GetCodes returns the Codes field value if set, zero value otherwise.
func (o *DefaultMessageSourceResolvable) GetCodes() []string {
	if o == nil || IsNil(o.Codes) {
		var ret []string
		return ret
	}
	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultMessageSourceResolvable) GetCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.Codes) {
		return nil, false
	}
	return o.Codes, true
}

// HasCodes returns a boolean if a field has been set.
func (o *DefaultMessageSourceResolvable) HasCodes() bool {
	if o != nil && !IsNil(o.Codes) {
		return true
	}

	return false
}

// SetCodes gets a reference to the given []string and assigns it to the Codes field.
func (o *DefaultMessageSourceResolvable) SetCodes(v []string) {
	o.Codes = v
}

// GetArguments returns the Arguments field value if set, zero value otherwise.
func (o *DefaultMessageSourceResolvable) GetArguments() []map[string]interface{} {
	if o == nil || IsNil(o.Arguments) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Arguments
}

// GetArgumentsOk returns a tuple with the Arguments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultMessageSourceResolvable) GetArgumentsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Arguments) {
		return nil, false
	}
	return o.Arguments, true
}

// HasArguments returns a boolean if a field has been set.
func (o *DefaultMessageSourceResolvable) HasArguments() bool {
	if o != nil && !IsNil(o.Arguments) {
		return true
	}

	return false
}

// SetArguments gets a reference to the given []map[string]interface{} and assigns it to the Arguments field.
func (o *DefaultMessageSourceResolvable) SetArguments(v []map[string]interface{}) {
	o.Arguments = v
}

// GetDefaultMessage returns the DefaultMessage field value if set, zero value otherwise.
func (o *DefaultMessageSourceResolvable) GetDefaultMessage() string {
	if o == nil || IsNil(o.DefaultMessage) {
		var ret string
		return ret
	}
	return *o.DefaultMessage
}

// GetDefaultMessageOk returns a tuple with the DefaultMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultMessageSourceResolvable) GetDefaultMessageOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultMessage) {
		return nil, false
	}
	return o.DefaultMessage, true
}

// HasDefaultMessage returns a boolean if a field has been set.
func (o *DefaultMessageSourceResolvable) HasDefaultMessage() bool {
	if o != nil && !IsNil(o.DefaultMessage) {
		return true
	}

	return false
}

// SetDefaultMessage gets a reference to the given string and assigns it to the DefaultMessage field.
func (o *DefaultMessageSourceResolvable) SetDefaultMessage(v string) {
	o.DefaultMessage = &v
}

func (o DefaultMessageSourceResolvable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultMessageSourceResolvable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Codes) {
		toSerialize["codes"] = o.Codes
	}
	if !IsNil(o.Arguments) {
		toSerialize["arguments"] = o.Arguments
	}
	if !IsNil(o.DefaultMessage) {
		toSerialize["defaultMessage"] = o.DefaultMessage
	}
	return toSerialize, nil
}

func (o *DefaultMessageSourceResolvable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultMessageSourceResolvable := _DefaultMessageSourceResolvable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultMessageSourceResolvable)

	if err != nil {
		return err
	}

	*o = DefaultMessageSourceResolvable(varDefaultMessageSourceResolvable)

	return err
}

type NullableDefaultMessageSourceResolvable struct {
	value *DefaultMessageSourceResolvable
	isSet bool
}

func (v NullableDefaultMessageSourceResolvable) Get() *DefaultMessageSourceResolvable {
	return v.value
}

func (v *NullableDefaultMessageSourceResolvable) Set(val *DefaultMessageSourceResolvable) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultMessageSourceResolvable) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultMessageSourceResolvable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultMessageSourceResolvable(val *DefaultMessageSourceResolvable) *NullableDefaultMessageSourceResolvable {
	return &NullableDefaultMessageSourceResolvable{value: val, isSet: true}
}

func (v NullableDefaultMessageSourceResolvable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultMessageSourceResolvable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


