/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiProjectImportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiProjectImportRequest{}

// ApiProjectImportRequest struct for ApiProjectImportRequest
type ApiProjectImportRequest struct {
	ArchiveParams *ProjectArchiveParams `json:"archiveParams,omitempty"`
}

// NewApiProjectImportRequest instantiates a new ApiProjectImportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiProjectImportRequest() *ApiProjectImportRequest {
	this := ApiProjectImportRequest{}
	return &this
}

// NewApiProjectImportRequestWithDefaults instantiates a new ApiProjectImportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiProjectImportRequestWithDefaults() *ApiProjectImportRequest {
	this := ApiProjectImportRequest{}
	return &this
}

// GetArchiveParams returns the ArchiveParams field value if set, zero value otherwise.
func (o *ApiProjectImportRequest) GetArchiveParams() ProjectArchiveParams {
	if o == nil || IsNil(o.ArchiveParams) {
		var ret ProjectArchiveParams
		return ret
	}
	return *o.ArchiveParams
}

// GetArchiveParamsOk returns a tuple with the ArchiveParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProjectImportRequest) GetArchiveParamsOk() (*ProjectArchiveParams, bool) {
	if o == nil || IsNil(o.ArchiveParams) {
		return nil, false
	}
	return o.ArchiveParams, true
}

// HasArchiveParams returns a boolean if a field has been set.
func (o *ApiProjectImportRequest) HasArchiveParams() bool {
	if o != nil && !IsNil(o.ArchiveParams) {
		return true
	}

	return false
}

// SetArchiveParams gets a reference to the given ProjectArchiveParams and assigns it to the ArchiveParams field.
func (o *ApiProjectImportRequest) SetArchiveParams(v ProjectArchiveParams) {
	o.ArchiveParams = &v
}

func (o ApiProjectImportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiProjectImportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArchiveParams) {
		toSerialize["archiveParams"] = o.ArchiveParams
	}
	return toSerialize, nil
}

type NullableApiProjectImportRequest struct {
	value *ApiProjectImportRequest
	isSet bool
}

func (v NullableApiProjectImportRequest) Get() *ApiProjectImportRequest {
	return v.value
}

func (v *NullableApiProjectImportRequest) Set(val *ApiProjectImportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiProjectImportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiProjectImportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiProjectImportRequest(val *ApiProjectImportRequest) *NullableApiProjectImportRequest {
	return &NullableApiProjectImportRequest{value: val, isSet: true}
}

func (v NullableApiProjectImportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiProjectImportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


