/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SaveProjectContextRunnerConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SaveProjectContextRunnerConfigRequest{}

// SaveProjectContextRunnerConfigRequest struct for SaveProjectContextRunnerConfigRequest
type SaveProjectContextRunnerConfigRequest struct {
	Project *string `json:"project,omitempty"`
	Automatic *bool `json:"automatic,omitempty"`
	RunnerConfigRequest *SaveProjectRunnerConfigRequest `json:"runnerConfigRequest,omitempty"`
}

// NewSaveProjectContextRunnerConfigRequest instantiates a new SaveProjectContextRunnerConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSaveProjectContextRunnerConfigRequest() *SaveProjectContextRunnerConfigRequest {
	this := SaveProjectContextRunnerConfigRequest{}
	return &this
}

// NewSaveProjectContextRunnerConfigRequestWithDefaults instantiates a new SaveProjectContextRunnerConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSaveProjectContextRunnerConfigRequestWithDefaults() *SaveProjectContextRunnerConfigRequest {
	this := SaveProjectContextRunnerConfigRequest{}
	return &this
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *SaveProjectContextRunnerConfigRequest) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaveProjectContextRunnerConfigRequest) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *SaveProjectContextRunnerConfigRequest) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *SaveProjectContextRunnerConfigRequest) SetProject(v string) {
	o.Project = &v
}

// GetAutomatic returns the Automatic field value if set, zero value otherwise.
func (o *SaveProjectContextRunnerConfigRequest) GetAutomatic() bool {
	if o == nil || IsNil(o.Automatic) {
		var ret bool
		return ret
	}
	return *o.Automatic
}

// GetAutomaticOk returns a tuple with the Automatic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaveProjectContextRunnerConfigRequest) GetAutomaticOk() (*bool, bool) {
	if o == nil || IsNil(o.Automatic) {
		return nil, false
	}
	return o.Automatic, true
}

// HasAutomatic returns a boolean if a field has been set.
func (o *SaveProjectContextRunnerConfigRequest) HasAutomatic() bool {
	if o != nil && !IsNil(o.Automatic) {
		return true
	}

	return false
}

// SetAutomatic gets a reference to the given bool and assigns it to the Automatic field.
func (o *SaveProjectContextRunnerConfigRequest) SetAutomatic(v bool) {
	o.Automatic = &v
}

// GetRunnerConfigRequest returns the RunnerConfigRequest field value if set, zero value otherwise.
func (o *SaveProjectContextRunnerConfigRequest) GetRunnerConfigRequest() SaveProjectRunnerConfigRequest {
	if o == nil || IsNil(o.RunnerConfigRequest) {
		var ret SaveProjectRunnerConfigRequest
		return ret
	}
	return *o.RunnerConfigRequest
}

// GetRunnerConfigRequestOk returns a tuple with the RunnerConfigRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SaveProjectContextRunnerConfigRequest) GetRunnerConfigRequestOk() (*SaveProjectRunnerConfigRequest, bool) {
	if o == nil || IsNil(o.RunnerConfigRequest) {
		return nil, false
	}
	return o.RunnerConfigRequest, true
}

// HasRunnerConfigRequest returns a boolean if a field has been set.
func (o *SaveProjectContextRunnerConfigRequest) HasRunnerConfigRequest() bool {
	if o != nil && !IsNil(o.RunnerConfigRequest) {
		return true
	}

	return false
}

// SetRunnerConfigRequest gets a reference to the given SaveProjectRunnerConfigRequest and assigns it to the RunnerConfigRequest field.
func (o *SaveProjectContextRunnerConfigRequest) SetRunnerConfigRequest(v SaveProjectRunnerConfigRequest) {
	o.RunnerConfigRequest = &v
}

func (o SaveProjectContextRunnerConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SaveProjectContextRunnerConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Automatic) {
		toSerialize["automatic"] = o.Automatic
	}
	if !IsNil(o.RunnerConfigRequest) {
		toSerialize["runnerConfigRequest"] = o.RunnerConfigRequest
	}
	return toSerialize, nil
}

type NullableSaveProjectContextRunnerConfigRequest struct {
	value *SaveProjectContextRunnerConfigRequest
	isSet bool
}

func (v NullableSaveProjectContextRunnerConfigRequest) Get() *SaveProjectContextRunnerConfigRequest {
	return v.value
}

func (v *NullableSaveProjectContextRunnerConfigRequest) Set(val *SaveProjectContextRunnerConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSaveProjectContextRunnerConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSaveProjectContextRunnerConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaveProjectContextRunnerConfigRequest(val *SaveProjectContextRunnerConfigRequest) *NullableSaveProjectContextRunnerConfigRequest {
	return &NullableSaveProjectContextRunnerConfigRequest{value: val, isSet: true}
}

func (v NullableSaveProjectContextRunnerConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaveProjectContextRunnerConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


