/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiExecutionModeLaterPassiveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiExecutionModeLaterPassiveRequest{}

// ApiExecutionModeLaterPassiveRequest struct for ApiExecutionModeLaterPassiveRequest
type ApiExecutionModeLaterPassiveRequest struct {
	// Time duration expression.  A series of: an integer followed by a unit.  Units: * `s` - seconds (default) * `m` - minutes * `h` - hours * `d` - days * `w` - weeks * `y` - years.  Examples: `1d12h`, `3600` (defaults to seconds), `15m30s`. 
	Value *string `json:"value,omitempty" validate:"regexp=((\\d+)[smhdwy]?)+"`
	Command *ExecutionModeLaterCommand `json:"command,omitempty"`
}

// NewApiExecutionModeLaterPassiveRequest instantiates a new ApiExecutionModeLaterPassiveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiExecutionModeLaterPassiveRequest() *ApiExecutionModeLaterPassiveRequest {
	this := ApiExecutionModeLaterPassiveRequest{}
	return &this
}

// NewApiExecutionModeLaterPassiveRequestWithDefaults instantiates a new ApiExecutionModeLaterPassiveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiExecutionModeLaterPassiveRequestWithDefaults() *ApiExecutionModeLaterPassiveRequest {
	this := ApiExecutionModeLaterPassiveRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ApiExecutionModeLaterPassiveRequest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecutionModeLaterPassiveRequest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ApiExecutionModeLaterPassiveRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ApiExecutionModeLaterPassiveRequest) SetValue(v string) {
	o.Value = &v
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *ApiExecutionModeLaterPassiveRequest) GetCommand() ExecutionModeLaterCommand {
	if o == nil || IsNil(o.Command) {
		var ret ExecutionModeLaterCommand
		return ret
	}
	return *o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiExecutionModeLaterPassiveRequest) GetCommandOk() (*ExecutionModeLaterCommand, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *ApiExecutionModeLaterPassiveRequest) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given ExecutionModeLaterCommand and assigns it to the Command field.
func (o *ApiExecutionModeLaterPassiveRequest) SetCommand(v ExecutionModeLaterCommand) {
	o.Command = &v
}

func (o ApiExecutionModeLaterPassiveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiExecutionModeLaterPassiveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	return toSerialize, nil
}

type NullableApiExecutionModeLaterPassiveRequest struct {
	value *ApiExecutionModeLaterPassiveRequest
	isSet bool
}

func (v NullableApiExecutionModeLaterPassiveRequest) Get() *ApiExecutionModeLaterPassiveRequest {
	return v.value
}

func (v *NullableApiExecutionModeLaterPassiveRequest) Set(val *ApiExecutionModeLaterPassiveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiExecutionModeLaterPassiveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiExecutionModeLaterPassiveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiExecutionModeLaterPassiveRequest(val *ApiExecutionModeLaterPassiveRequest) *NullableApiExecutionModeLaterPassiveRequest {
	return &NullableApiExecutionModeLaterPassiveRequest{value: val, isSet: true}
}

func (v NullableApiExecutionModeLaterPassiveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiExecutionModeLaterPassiveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


