/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AuthorizationsResponseAuthorizationContext - struct for AuthorizationsResponseAuthorizationContext
type AuthorizationsResponseAuthorizationContext struct {
	ApplicationAuthorizationContext *ApplicationAuthorizationContext
	ProjectAuthorizationContext *ProjectAuthorizationContext
}

// ApplicationAuthorizationContextAsAuthorizationsResponseAuthorizationContext is a convenience function that returns ApplicationAuthorizationContext wrapped in AuthorizationsResponseAuthorizationContext
func ApplicationAuthorizationContextAsAuthorizationsResponseAuthorizationContext(v *ApplicationAuthorizationContext) AuthorizationsResponseAuthorizationContext {
	return AuthorizationsResponseAuthorizationContext{
		ApplicationAuthorizationContext: v,
	}
}

// ProjectAuthorizationContextAsAuthorizationsResponseAuthorizationContext is a convenience function that returns ProjectAuthorizationContext wrapped in AuthorizationsResponseAuthorizationContext
func ProjectAuthorizationContextAsAuthorizationsResponseAuthorizationContext(v *ProjectAuthorizationContext) AuthorizationsResponseAuthorizationContext {
	return AuthorizationsResponseAuthorizationContext{
		ProjectAuthorizationContext: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AuthorizationsResponseAuthorizationContext) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ApplicationAuthorizationContext
	err = newStrictDecoder(data).Decode(&dst.ApplicationAuthorizationContext)
	if err == nil {
		jsonApplicationAuthorizationContext, _ := json.Marshal(dst.ApplicationAuthorizationContext)
		if string(jsonApplicationAuthorizationContext) == "{}" { // empty struct
			dst.ApplicationAuthorizationContext = nil
		} else {
			if err = validator.Validate(dst.ApplicationAuthorizationContext); err != nil {
				dst.ApplicationAuthorizationContext = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApplicationAuthorizationContext = nil
	}

	// try to unmarshal data into ProjectAuthorizationContext
	err = newStrictDecoder(data).Decode(&dst.ProjectAuthorizationContext)
	if err == nil {
		jsonProjectAuthorizationContext, _ := json.Marshal(dst.ProjectAuthorizationContext)
		if string(jsonProjectAuthorizationContext) == "{}" { // empty struct
			dst.ProjectAuthorizationContext = nil
		} else {
			if err = validator.Validate(dst.ProjectAuthorizationContext); err != nil {
				dst.ProjectAuthorizationContext = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProjectAuthorizationContext = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ApplicationAuthorizationContext = nil
		dst.ProjectAuthorizationContext = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AuthorizationsResponseAuthorizationContext)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(AuthorizationsResponseAuthorizationContext): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(AuthorizationsResponseAuthorizationContext)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AuthorizationsResponseAuthorizationContext) MarshalJSON() ([]byte, error) {
	if src.ApplicationAuthorizationContext != nil {
		return json.Marshal(&src.ApplicationAuthorizationContext)
	}

	if src.ProjectAuthorizationContext != nil {
		return json.Marshal(&src.ProjectAuthorizationContext)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AuthorizationsResponseAuthorizationContext) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApplicationAuthorizationContext != nil {
		return obj.ApplicationAuthorizationContext
	}

	if obj.ProjectAuthorizationContext != nil {
		return obj.ProjectAuthorizationContext
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AuthorizationsResponseAuthorizationContext) GetActualInstanceValue() (interface{}) {
	if obj.ApplicationAuthorizationContext != nil {
		return *obj.ApplicationAuthorizationContext
	}

	if obj.ProjectAuthorizationContext != nil {
		return *obj.ProjectAuthorizationContext
	}

	// all schemas are nil
	return nil
}

type NullableAuthorizationsResponseAuthorizationContext struct {
	value *AuthorizationsResponseAuthorizationContext
	isSet bool
}

func (v NullableAuthorizationsResponseAuthorizationContext) Get() *AuthorizationsResponseAuthorizationContext {
	return v.value
}

func (v *NullableAuthorizationsResponseAuthorizationContext) Set(val *AuthorizationsResponseAuthorizationContext) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationsResponseAuthorizationContext) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationsResponseAuthorizationContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationsResponseAuthorizationContext(val *AuthorizationsResponseAuthorizationContext) *NullableAuthorizationsResponseAuthorizationContext {
	return &NullableAuthorizationsResponseAuthorizationContext{value: val, isSet: true}
}

func (v NullableAuthorizationsResponseAuthorizationContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationsResponseAuthorizationContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


