/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration

API version: 56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StartUpResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartUpResponse{}

// StartUpResponse struct for StartUpResponse
type StartUpResponse struct {
	Error *bool `json:"error,omitempty"`
	ReplicaId *string `json:"replicaId,omitempty"`
	ReplicaType *string `json:"replicaType,omitempty"`
}

// NewStartUpResponse instantiates a new StartUpResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartUpResponse() *StartUpResponse {
	this := StartUpResponse{}
	return &this
}

// NewStartUpResponseWithDefaults instantiates a new StartUpResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartUpResponseWithDefaults() *StartUpResponse {
	this := StartUpResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *StartUpResponse) GetError() bool {
	if o == nil || IsNil(o.Error) {
		var ret bool
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartUpResponse) GetErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *StartUpResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given bool and assigns it to the Error field.
func (o *StartUpResponse) SetError(v bool) {
	o.Error = &v
}

// GetReplicaId returns the ReplicaId field value if set, zero value otherwise.
func (o *StartUpResponse) GetReplicaId() string {
	if o == nil || IsNil(o.ReplicaId) {
		var ret string
		return ret
	}
	return *o.ReplicaId
}

// GetReplicaIdOk returns a tuple with the ReplicaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartUpResponse) GetReplicaIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReplicaId) {
		return nil, false
	}
	return o.ReplicaId, true
}

// HasReplicaId returns a boolean if a field has been set.
func (o *StartUpResponse) HasReplicaId() bool {
	if o != nil && !IsNil(o.ReplicaId) {
		return true
	}

	return false
}

// SetReplicaId gets a reference to the given string and assigns it to the ReplicaId field.
func (o *StartUpResponse) SetReplicaId(v string) {
	o.ReplicaId = &v
}

// GetReplicaType returns the ReplicaType field value if set, zero value otherwise.
func (o *StartUpResponse) GetReplicaType() string {
	if o == nil || IsNil(o.ReplicaType) {
		var ret string
		return ret
	}
	return *o.ReplicaType
}

// GetReplicaTypeOk returns a tuple with the ReplicaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartUpResponse) GetReplicaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ReplicaType) {
		return nil, false
	}
	return o.ReplicaType, true
}

// HasReplicaType returns a boolean if a field has been set.
func (o *StartUpResponse) HasReplicaType() bool {
	if o != nil && !IsNil(o.ReplicaType) {
		return true
	}

	return false
}

// SetReplicaType gets a reference to the given string and assigns it to the ReplicaType field.
func (o *StartUpResponse) SetReplicaType(v string) {
	o.ReplicaType = &v
}

func (o StartUpResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartUpResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.ReplicaId) {
		toSerialize["replicaId"] = o.ReplicaId
	}
	if !IsNil(o.ReplicaType) {
		toSerialize["replicaType"] = o.ReplicaType
	}
	return toSerialize, nil
}

type NullableStartUpResponse struct {
	value *StartUpResponse
	isSet bool
}

func (v NullableStartUpResponse) Get() *StartUpResponse {
	return v.value
}

func (v *NullableStartUpResponse) Set(val *StartUpResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStartUpResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStartUpResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartUpResponse(val *StartUpResponse) *NullableStartUpResponse {
	return &NullableStartUpResponse{value: val, isSet: true}
}

func (v NullableStartUpResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartUpResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


