/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteBulkRequestLong type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteBulkRequestLong{}

// DeleteBulkRequestLong struct for DeleteBulkRequestLong
type DeleteBulkRequestLong struct {
	Ids []int64 `json:"ids,omitempty"`
}

// NewDeleteBulkRequestLong instantiates a new DeleteBulkRequestLong object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteBulkRequestLong() *DeleteBulkRequestLong {
	this := DeleteBulkRequestLong{}
	return &this
}

// NewDeleteBulkRequestLongWithDefaults instantiates a new DeleteBulkRequestLong object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteBulkRequestLongWithDefaults() *DeleteBulkRequestLong {
	this := DeleteBulkRequestLong{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *DeleteBulkRequestLong) GetIds() []int64 {
	if o == nil || IsNil(o.Ids) {
		var ret []int64
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteBulkRequestLong) GetIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *DeleteBulkRequestLong) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []int64 and assigns it to the Ids field.
func (o *DeleteBulkRequestLong) SetIds(v []int64) {
	o.Ids = v
}

func (o DeleteBulkRequestLong) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteBulkRequestLong) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	return toSerialize, nil
}

type NullableDeleteBulkRequestLong struct {
	value *DeleteBulkRequestLong
	isSet bool
}

func (v NullableDeleteBulkRequestLong) Get() *DeleteBulkRequestLong {
	return v.value
}

func (v *NullableDeleteBulkRequestLong) Set(val *DeleteBulkRequestLong) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteBulkRequestLong) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteBulkRequestLong) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteBulkRequestLong(val *DeleteBulkRequestLong) *NullableDeleteBulkRequestLong {
	return &NullableDeleteBulkRequestLong{value: val, isSet: true}
}

func (v NullableDeleteBulkRequestLong) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteBulkRequestLong) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


