/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TypeResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypeResource{}

// TypeResource A resource type with a specifier
type TypeResource struct {
	// Resource Type
	Type string `json:"type"`
	// Type Specifier
	Specifier *string `json:"specifier,omitempty"`
}

type _TypeResource TypeResource

// NewTypeResource instantiates a new TypeResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypeResource(type_ string) *TypeResource {
	this := TypeResource{}
	this.Type = type_
	return &this
}

// NewTypeResourceWithDefaults instantiates a new TypeResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypeResourceWithDefaults() *TypeResource {
	this := TypeResource{}
	return &this
}

// GetType returns the Type field value
func (o *TypeResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TypeResource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TypeResource) SetType(v string) {
	o.Type = v
}

// GetSpecifier returns the Specifier field value if set, zero value otherwise.
func (o *TypeResource) GetSpecifier() string {
	if o == nil || IsNil(o.Specifier) {
		var ret string
		return ret
	}
	return *o.Specifier
}

// GetSpecifierOk returns a tuple with the Specifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeResource) GetSpecifierOk() (*string, bool) {
	if o == nil || IsNil(o.Specifier) {
		return nil, false
	}
	return o.Specifier, true
}

// HasSpecifier returns a boolean if a field has been set.
func (o *TypeResource) HasSpecifier() bool {
	if o != nil && !IsNil(o.Specifier) {
		return true
	}

	return false
}

// SetSpecifier gets a reference to the given string and assigns it to the Specifier field.
func (o *TypeResource) SetSpecifier(v string) {
	o.Specifier = &v
}

func (o TypeResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypeResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Specifier) {
		toSerialize["specifier"] = o.Specifier
	}
	return toSerialize, nil
}

func (o *TypeResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypeResource := _TypeResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTypeResource)

	if err != nil {
		return err
	}

	*o = TypeResource(varTypeResource)

	return err
}

type NullableTypeResource struct {
	value *TypeResource
	isSet bool
}

func (v NullableTypeResource) Get() *TypeResource {
	return v.value
}

func (v *NullableTypeResource) Set(val *TypeResource) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeResource) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeResource(val *TypeResource) *NullableTypeResource {
	return &NullableTypeResource{value: val, isSet: true}
}

func (v NullableTypeResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


