/*
Rundeck / Runbook Automation API

Rundeck / Runbook Automation REST API for job automation, execution management, and system administration.  The Rundeck API provides comprehensive access to: - Job management (create, update, delete, execute jobs) - Execution monitoring and control - Project and resource management - Node filtering and resource queries - System configuration and administration - SCM integration (Git and other version control) - Authentication token management - Metrics and health monitoring  All API endpoints require authentication via API token, password session, or JWT token (Enterprise). API version must be specified in the URL path (e.g., /api/46/...).  For detailed documentation, see: [Rundeck API Docs](https://docs.rundeck.com/docs/api/)

API version: 59
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SystemInfoModelSystemInfoSystem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemInfoModelSystemInfoSystem{}

// SystemInfoModelSystemInfoSystem System Information
type SystemInfoModelSystemInfoSystem struct {
	Timestamp *Timestamp `json:"timestamp,omitempty"`
	Rundeck *Rundeck `json:"rundeck,omitempty"`
	Executions *Executions `json:"executions,omitempty"`
	Os *Os `json:"os,omitempty"`
	Jvm *Jvm `json:"jvm,omitempty"`
	Stats *Stats `json:"stats,omitempty"`
	Metrics *Metrics `json:"metrics,omitempty"`
	ThreadDump *ThreadDump `json:"threadDump,omitempty"`
	Healthcheck *Healthcheck `json:"healthcheck,omitempty"`
	Ping *Ping `json:"ping,omitempty"`
	Extended map[string]map[string]interface{} `json:"extended,omitempty"`
}

// NewSystemInfoModelSystemInfoSystem instantiates a new SystemInfoModelSystemInfoSystem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInfoModelSystemInfoSystem() *SystemInfoModelSystemInfoSystem {
	this := SystemInfoModelSystemInfoSystem{}
	return &this
}

// NewSystemInfoModelSystemInfoSystemWithDefaults instantiates a new SystemInfoModelSystemInfoSystem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInfoModelSystemInfoSystemWithDefaults() *SystemInfoModelSystemInfoSystem {
	this := SystemInfoModelSystemInfoSystem{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetTimestamp() Timestamp {
	if o == nil || IsNil(o.Timestamp) {
		var ret Timestamp
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetTimestampOk() (*Timestamp, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given Timestamp and assigns it to the Timestamp field.
func (o *SystemInfoModelSystemInfoSystem) SetTimestamp(v Timestamp) {
	o.Timestamp = &v
}

// GetRundeck returns the Rundeck field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetRundeck() Rundeck {
	if o == nil || IsNil(o.Rundeck) {
		var ret Rundeck
		return ret
	}
	return *o.Rundeck
}

// GetRundeckOk returns a tuple with the Rundeck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetRundeckOk() (*Rundeck, bool) {
	if o == nil || IsNil(o.Rundeck) {
		return nil, false
	}
	return o.Rundeck, true
}

// HasRundeck returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasRundeck() bool {
	if o != nil && !IsNil(o.Rundeck) {
		return true
	}

	return false
}

// SetRundeck gets a reference to the given Rundeck and assigns it to the Rundeck field.
func (o *SystemInfoModelSystemInfoSystem) SetRundeck(v Rundeck) {
	o.Rundeck = &v
}

// GetExecutions returns the Executions field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetExecutions() Executions {
	if o == nil || IsNil(o.Executions) {
		var ret Executions
		return ret
	}
	return *o.Executions
}

// GetExecutionsOk returns a tuple with the Executions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetExecutionsOk() (*Executions, bool) {
	if o == nil || IsNil(o.Executions) {
		return nil, false
	}
	return o.Executions, true
}

// HasExecutions returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasExecutions() bool {
	if o != nil && !IsNil(o.Executions) {
		return true
	}

	return false
}

// SetExecutions gets a reference to the given Executions and assigns it to the Executions field.
func (o *SystemInfoModelSystemInfoSystem) SetExecutions(v Executions) {
	o.Executions = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetOs() Os {
	if o == nil || IsNil(o.Os) {
		var ret Os
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetOsOk() (*Os, bool) {
	if o == nil || IsNil(o.Os) {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasOs() bool {
	if o != nil && !IsNil(o.Os) {
		return true
	}

	return false
}

// SetOs gets a reference to the given Os and assigns it to the Os field.
func (o *SystemInfoModelSystemInfoSystem) SetOs(v Os) {
	o.Os = &v
}

// GetJvm returns the Jvm field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetJvm() Jvm {
	if o == nil || IsNil(o.Jvm) {
		var ret Jvm
		return ret
	}
	return *o.Jvm
}

// GetJvmOk returns a tuple with the Jvm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetJvmOk() (*Jvm, bool) {
	if o == nil || IsNil(o.Jvm) {
		return nil, false
	}
	return o.Jvm, true
}

// HasJvm returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasJvm() bool {
	if o != nil && !IsNil(o.Jvm) {
		return true
	}

	return false
}

// SetJvm gets a reference to the given Jvm and assigns it to the Jvm field.
func (o *SystemInfoModelSystemInfoSystem) SetJvm(v Jvm) {
	o.Jvm = &v
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetStats() Stats {
	if o == nil || IsNil(o.Stats) {
		var ret Stats
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetStatsOk() (*Stats, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given Stats and assigns it to the Stats field.
func (o *SystemInfoModelSystemInfoSystem) SetStats(v Stats) {
	o.Stats = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetMetrics() Metrics {
	if o == nil || IsNil(o.Metrics) {
		var ret Metrics
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetMetricsOk() (*Metrics, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given Metrics and assigns it to the Metrics field.
func (o *SystemInfoModelSystemInfoSystem) SetMetrics(v Metrics) {
	o.Metrics = &v
}

// GetThreadDump returns the ThreadDump field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetThreadDump() ThreadDump {
	if o == nil || IsNil(o.ThreadDump) {
		var ret ThreadDump
		return ret
	}
	return *o.ThreadDump
}

// GetThreadDumpOk returns a tuple with the ThreadDump field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetThreadDumpOk() (*ThreadDump, bool) {
	if o == nil || IsNil(o.ThreadDump) {
		return nil, false
	}
	return o.ThreadDump, true
}

// HasThreadDump returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasThreadDump() bool {
	if o != nil && !IsNil(o.ThreadDump) {
		return true
	}

	return false
}

// SetThreadDump gets a reference to the given ThreadDump and assigns it to the ThreadDump field.
func (o *SystemInfoModelSystemInfoSystem) SetThreadDump(v ThreadDump) {
	o.ThreadDump = &v
}

// GetHealthcheck returns the Healthcheck field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetHealthcheck() Healthcheck {
	if o == nil || IsNil(o.Healthcheck) {
		var ret Healthcheck
		return ret
	}
	return *o.Healthcheck
}

// GetHealthcheckOk returns a tuple with the Healthcheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetHealthcheckOk() (*Healthcheck, bool) {
	if o == nil || IsNil(o.Healthcheck) {
		return nil, false
	}
	return o.Healthcheck, true
}

// HasHealthcheck returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasHealthcheck() bool {
	if o != nil && !IsNil(o.Healthcheck) {
		return true
	}

	return false
}

// SetHealthcheck gets a reference to the given Healthcheck and assigns it to the Healthcheck field.
func (o *SystemInfoModelSystemInfoSystem) SetHealthcheck(v Healthcheck) {
	o.Healthcheck = &v
}

// GetPing returns the Ping field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetPing() Ping {
	if o == nil || IsNil(o.Ping) {
		var ret Ping
		return ret
	}
	return *o.Ping
}

// GetPingOk returns a tuple with the Ping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetPingOk() (*Ping, bool) {
	if o == nil || IsNil(o.Ping) {
		return nil, false
	}
	return o.Ping, true
}

// HasPing returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasPing() bool {
	if o != nil && !IsNil(o.Ping) {
		return true
	}

	return false
}

// SetPing gets a reference to the given Ping and assigns it to the Ping field.
func (o *SystemInfoModelSystemInfoSystem) SetPing(v Ping) {
	o.Ping = &v
}

// GetExtended returns the Extended field value if set, zero value otherwise.
func (o *SystemInfoModelSystemInfoSystem) GetExtended() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Extended) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Extended
}

// GetExtendedOk returns a tuple with the Extended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInfoModelSystemInfoSystem) GetExtendedOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Extended) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Extended, true
}

// HasExtended returns a boolean if a field has been set.
func (o *SystemInfoModelSystemInfoSystem) HasExtended() bool {
	if o != nil && !IsNil(o.Extended) {
		return true
	}

	return false
}

// SetExtended gets a reference to the given map[string]map[string]interface{} and assigns it to the Extended field.
func (o *SystemInfoModelSystemInfoSystem) SetExtended(v map[string]map[string]interface{}) {
	o.Extended = v
}

func (o SystemInfoModelSystemInfoSystem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemInfoModelSystemInfoSystem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Rundeck) {
		toSerialize["rundeck"] = o.Rundeck
	}
	if !IsNil(o.Executions) {
		toSerialize["executions"] = o.Executions
	}
	if !IsNil(o.Os) {
		toSerialize["os"] = o.Os
	}
	if !IsNil(o.Jvm) {
		toSerialize["jvm"] = o.Jvm
	}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.ThreadDump) {
		toSerialize["threadDump"] = o.ThreadDump
	}
	if !IsNil(o.Healthcheck) {
		toSerialize["healthcheck"] = o.Healthcheck
	}
	if !IsNil(o.Ping) {
		toSerialize["ping"] = o.Ping
	}
	if !IsNil(o.Extended) {
		toSerialize["extended"] = o.Extended
	}
	return toSerialize, nil
}

type NullableSystemInfoModelSystemInfoSystem struct {
	value *SystemInfoModelSystemInfoSystem
	isSet bool
}

func (v NullableSystemInfoModelSystemInfoSystem) Get() *SystemInfoModelSystemInfoSystem {
	return v.value
}

func (v *NullableSystemInfoModelSystemInfoSystem) Set(val *SystemInfoModelSystemInfoSystem) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInfoModelSystemInfoSystem) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInfoModelSystemInfoSystem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInfoModelSystemInfoSystem(val *SystemInfoModelSystemInfoSystem) *NullableSystemInfoModelSystemInfoSystem {
	return &NullableSystemInfoModelSystemInfoSystem{value: val, isSet: true}
}

func (v NullableSystemInfoModelSystemInfoSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInfoModelSystemInfoSystem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


