/*
Rundeck / Runbook Automation API

Testing HealthAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_HealthAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HealthAPIService ApiNodeHealth", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.HealthAPI.ApiNodeHealth(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthAPIService ApiNodeHealthAll", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.HealthAPI.ApiNodeHealthAll(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthAPIService ApiProjectHasHealthStatusEnhancer", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.HealthAPI.ApiProjectHasHealthStatusEnhancer(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthAPIService ApiRefreshHealthCheck", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.HealthAPI.ApiRefreshHealthCheck(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthAPIService ApiRefreshHealthCheckAll", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.HealthAPI.ApiRefreshHealthCheckAll(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
