/*
Rundeck / Runbook Automation API

Testing CalendarsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_CalendarsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CalendarsAPIService ApiDeleteProjectCalendar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var id string

		httpRes, err := apiClient.CalendarsAPI.ApiDeleteProjectCalendar(context.Background(), project, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarsAPIService ApiDeleteSystemCalendar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		httpRes, err := apiClient.CalendarsAPI.ApiDeleteSystemCalendar(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarsAPIService ApiLoadProjectCalendars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.CalendarsAPI.ApiLoadProjectCalendars(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarsAPIService ApiLoadSystemCalendars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CalendarsAPI.ApiLoadSystemCalendars(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarsAPIService ApiProjectCalendars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.CalendarsAPI.ApiProjectCalendars(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarsAPIService ApiSystemCalendars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CalendarsAPI.ApiSystemCalendars(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
