/*
Rundeck / Runbook Automation API

Testing ExecutionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
)

func Test_openapi_ExecutionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ExecutionAPIService ApiExecution", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ExecutionAPI.ApiExecution(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionAbort", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ExecutionAPI.ApiExecutionAbort(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ExecutionAPI.ApiExecutionDelete(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionDeleteBulk", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionDeleteBulk(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionInputFiles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionInputFiles(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionMetricsDocs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionMetricsDocs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionMetricsProjectDocs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionMetricsProjectDocs(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionMetricsProjectDocs_1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionMetricsProjectDocs_0(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionOutput", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionOutput(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionOutputNodeFilter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var nodename string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionOutputNodeFilter(context.Background(), id, nodename).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionOutputNodeStepFilter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var nodename string
		var stepctx string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionOutputNodeStepFilter(context.Background(), id, nodename, stepctx).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionOutputStepFilter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var stepctx string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionOutputStepFilter(context.Background(), id, stepctx).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionState", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionState(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionStateOutput", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionStateOutput(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionsQueryv14Docs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		httpRes, err := apiClient.ExecutionAPI.ApiExecutionsQueryv14Docs(context.Background(), project).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiExecutionsRunningv14", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ExecutionAPI.ApiExecutionsRunningv14(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExecutionAPIService ApiHomeSummary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ExecutionAPI.ApiHomeSummary(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
