/*
Rundeck / Runbook Automation API

Testing RunnerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_RunnerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RunnerAPIService CheckPing", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var token string

		resp, httpRes, err := apiClient.RunnerAPI.CheckPing(context.Background(), token).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService CreateNoEphemeralReplica", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.CreateNoEphemeralReplica(context.Background(), runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService CreateProjectNoEphemeralReplica", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.CreateProjectNoEphemeralReplica(context.Background(), project, runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService CreateProjectRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.RunnerAPI.CreateProjectRunner(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService CreateRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerAPI.CreateRunner(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService DeleteProjectRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var runnerId string

		httpRes, err := apiClient.RunnerAPI.DeleteProjectRunner(context.Background(), project, runnerId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService DeleteProjectRunnerReplica", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var runnerId string
		var replicaId string

		httpRes, err := apiClient.RunnerAPI.DeleteProjectRunnerReplica(context.Background(), project, runnerId, replicaId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService DeleteRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string

		httpRes, err := apiClient.RunnerAPI.DeleteRunner(context.Background(), runnerId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService DeleteRunnerReplica", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string
		var replicaId string

		httpRes, err := apiClient.RunnerAPI.DeleteRunnerReplica(context.Background(), runnerId, replicaId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService DownloadRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var token string

		httpRes, err := apiClient.RunnerAPI.DownloadRunner(context.Background(), token).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService GetRunnerKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		resp, httpRes, err := apiClient.RunnerAPI.GetRunnerKey(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ListProjectAssociatedTags", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerAPI.ListProjectAssociatedTags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ListProjectRunners", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.RunnerAPI.ListProjectRunners(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ListProjectRunnersReplicas", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.ListProjectRunnersReplicas(context.Background(), project, runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ListRunnerTags", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		resp, httpRes, err := apiClient.RunnerAPI.ListRunnerTags(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ListRunners", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerAPI.ListRunners(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ListRunnersReplicas", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.ListRunnersReplicas(context.Background(), runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService PingProjectRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var project string

		resp, httpRes, err := apiClient.RunnerAPI.PingProjectRunner(context.Background(), id, project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService PingRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		resp, httpRes, err := apiClient.RunnerAPI.PingRunner(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ProjectCheckPing", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var token string
		var project string

		resp, httpRes, err := apiClient.RunnerAPI.ProjectCheckPing(context.Background(), token, project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ProjectContextRunnerConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.RunnerAPI.ProjectContextRunnerConfig(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ProjectDownloadRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var token string
		var project string

		httpRes, err := apiClient.RunnerAPI.ProjectDownloadRunner(context.Background(), token, project).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ProjectRunnerInfo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string
		var project string

		resp, httpRes, err := apiClient.RunnerAPI.ProjectRunnerInfo(context.Background(), runnerId, project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService ProjectUi", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.RunnerAPI.ProjectUi(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService RegenerateProjectRunnerCreds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var id string

		resp, httpRes, err := apiClient.RunnerAPI.RegenerateProjectRunnerCreds(context.Background(), project, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService RegenerateRunnerCreds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		resp, httpRes, err := apiClient.RunnerAPI.RegenerateRunnerCreds(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService RemoveProjectAssociation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.RemoveProjectAssociation(context.Background(), project, runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService RunnerInfo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.RunnerInfo(context.Background(), runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService SaveProjectContextRunnerConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.RunnerAPI.SaveProjectContextRunnerConfig(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService SaveProjectRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.SaveProjectRunner(context.Background(), project, runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService SaveProjectRunnerNodeDispatchSettings", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.RunnerAPI.SaveProjectRunnerNodeDispatchSettings(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService SaveRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var runnerId string

		resp, httpRes, err := apiClient.RunnerAPI.SaveRunner(context.Background(), runnerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService SearchTags", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerAPI.SearchTags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService StartupOperation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerAPI.StartupOperation(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerAPIService Ui", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerAPI.Ui(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
