/*
Rundeck / Runbook Automation API

Testing JobExecutionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
)

func Test_openapi_JobExecutionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test JobExecutionsAPIService ApiExecution", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.JobExecutionsAPI.ApiExecution(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionAbort", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionAbort(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionDelete(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionDeleteBulk", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionDeleteBulk(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionInputFiles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionInputFiles(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionMetricsDocs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionMetricsDocs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionMetricsProjectDocs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionMetricsProjectDocs(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionOutput", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionOutput(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionOutputNodeFilter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var nodename string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionOutputNodeFilter(context.Background(), id, nodename).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionOutputNodeStepFilter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var nodename string
		var stepctx string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionOutputNodeStepFilter(context.Background(), id, nodename, stepctx).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionOutputStepFilter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var stepctx string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionOutputStepFilter(context.Background(), id, stepctx).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionState", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionState(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionStateOutput", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionStateOutput(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionsQueryv14Docs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionsQueryv14Docs(context.Background(), project).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiExecutionsRunningv14", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiExecutionsRunningv14(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JobExecutionsAPIService ApiHomeSummary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.JobExecutionsAPI.ApiHomeSummary(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
