/*
Rundeck / Runbook Automation API

Testing SCMAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_SCMAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SCMAPIService ApiJobActionInput", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var integration string
		var actionId string

		resp, httpRes, err := apiClient.SCMAPI.ApiJobActionInput(context.Background(), id, integration, actionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiJobActionPerform", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var integration string
		var actionId string

		resp, httpRes, err := apiClient.SCMAPI.ApiJobActionPerform(context.Background(), id, integration, actionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiJobDiff", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var integration string

		resp, httpRes, err := apiClient.SCMAPI.ApiJobDiff(context.Background(), id, integration).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiJobStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var integration string

		resp, httpRes, err := apiClient.SCMAPI.ApiJobStatus(context.Background(), id, integration).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiPluginInput", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string
		var type_ string

		resp, httpRes, err := apiClient.SCMAPI.ApiPluginInput(context.Background(), project, integration, type_).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiPlugins", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string

		resp, httpRes, err := apiClient.SCMAPI.ApiPlugins(context.Background(), project, integration).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectActionInput", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string
		var actionId string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectActionInput(context.Background(), project, integration, actionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectActionPerform", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string
		var actionId string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectActionPerform(context.Background(), project, integration, actionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectConfig(context.Background(), project, integration).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectDisable", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string
		var type_ string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectDisable(context.Background(), project, integration, type_).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectEnable", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string
		var type_ string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectEnable(context.Background(), project, integration, type_).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectSetup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string
		var type_ string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectSetup(context.Background(), project, integration, type_).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var integration string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectStatus(context.Background(), project, integration).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SCMAPIService ApiProjectToggleSCM", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.SCMAPI.ApiProjectToggleSCM(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
