/*
Rundeck / Runbook Automation API

Testing ProjectAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
)

func Test_openapi_ProjectAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProjectAPIService ApiProjectConfigGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectConfigGet(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectConfigKeyDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var keypath string

		httpRes, err := apiClient.ProjectAPI.ApiProjectConfigKeyDelete(context.Background(), project, keypath).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectConfigKeyGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var keypath string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectConfigKeyGet(context.Background(), project, keypath).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectConfigKeyPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var keypath string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectConfigKeyPut(context.Background(), project, keypath).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectConfigPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectConfigPut(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		httpRes, err := apiClient.ProjectAPI.ApiProjectDelete(context.Background(), project).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectDisableLater", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectDisableLater(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectEnableLater", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectEnableLater(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectExport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectExport(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectExportAsyncDocs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectExportAsyncDocs(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectExportAsyncDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var token string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectExportAsyncDownload(context.Background(), project, token).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectExportAsyncStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var token string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectExportAsyncStatus(context.Background(), project, token).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectFileDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var filename string

		httpRes, err := apiClient.ProjectAPI.ApiProjectFileDelete(context.Background(), project, filename).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectFileGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var filename string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectFileGet(context.Background(), project, filename).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectFilePut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var filename string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectFilePut(context.Background(), project, filename).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectGet(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectImport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectImport(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectList1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectList1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiProjectMeta", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiProjectMeta(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiResourcesv2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiResourcesv2(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiResourcev14", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.ProjectAPI.ApiResourcev14(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiSourceGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var index int32

		resp, httpRes, err := apiClient.ProjectAPI.ApiSourceGet(context.Background(), project, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiSourceGetContent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var index int32

		resp, httpRes, err := apiClient.ProjectAPI.ApiSourceGetContent(context.Background(), project, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiSourceWriteContent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var index int32

		resp, httpRes, err := apiClient.ProjectAPI.ApiSourceWriteContent(context.Background(), project, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiSourcesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiSourcesList(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService ApiTagsForNodes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		resp, httpRes, err := apiClient.ProjectAPI.ApiTagsForNodes(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectAPIService SaveProjectPlugins", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string

		httpRes, err := apiClient.ProjectAPI.SaveProjectPlugins(context.Background(), project).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
