/*
Rundeck / Runbook Automation API

Testing AuthorizationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_AuthorizationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AuthorizationAPIService AppContextAuthorizationsForResourceKind", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var kind string

		resp, httpRes, err := apiClient.AuthorizationAPI.AppContextAuthorizationsForResourceKind(context.Background(), kind).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthorizationAPIService AppContextAuthorizationsForTypeWithSpecifier", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var type_ string
		var specifier string

		resp, httpRes, err := apiClient.AuthorizationAPI.AppContextAuthorizationsForTypeWithSpecifier(context.Background(), type_, specifier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthorizationAPIService ProjectContextAuthorizationsForJob", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var specifier string

		resp, httpRes, err := apiClient.AuthorizationAPI.ProjectContextAuthorizationsForJob(context.Background(), project, specifier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthorizationAPIService ProjectContextAuthorizationsForResourceKind", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var kind string

		resp, httpRes, err := apiClient.AuthorizationAPI.ProjectContextAuthorizationsForResourceKind(context.Background(), project, kind).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthorizationAPIService ProjectContextAuthorizationsForTypeWithSpecifier", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var type_ string
		var specifier string

		resp, httpRes, err := apiClient.AuthorizationAPI.ProjectContextAuthorizationsForTypeWithSpecifier(context.Background(), project, type_, specifier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
