/*
Rundeck / Runbook Automation API

Testing ToursAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck/rundeck-v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_ToursAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ToursAPIService ApiGetProjectResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var path string

		resp, httpRes, err := apiClient.ToursAPI.ApiGetProjectResource(context.Background(), project, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiGetSystemResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var path string

		resp, httpRes, err := apiClient.ToursAPI.ApiGetSystemResource(context.Background(), path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiProjectImportTour", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var tourFolder string
		var manifestFileName string

		resp, httpRes, err := apiClient.ToursAPI.ApiProjectImportTour(context.Background(), project, tourFolder, manifestFileName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiProjectList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string

		resp, httpRes, err := apiClient.ToursAPI.ApiProjectList(context.Background(), project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiProjectLoadResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var project string
		var path string

		resp, httpRes, err := apiClient.ToursAPI.ApiProjectLoadResource(context.Background(), project, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiRundeckEndpoints", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ToursAPI.ApiRundeckEndpoints(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiSystemImportTour", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tourFolder string
		var manifestFileName string

		resp, httpRes, err := apiClient.ToursAPI.ApiSystemImportTour(context.Background(), tourFolder, manifestFileName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiSystemList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ToursAPI.ApiSystemList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ToursAPIService ApiSystemLoadResource", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var path string

		resp, httpRes, err := apiClient.ToursAPI.ApiSystemLoadResource(context.Background(), path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
