/*
Rundeck / Runbook Automation API

Testing TokensAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/rundeck/go-rundeck"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_TokensAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TokensAPIService ApiTokenCreate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var user string

		resp, httpRes, err := apiClient.TokensAPI.ApiTokenCreate(context.Background(), user).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TokensAPIService ApiTokenDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tokenid string

		resp, httpRes, err := apiClient.TokensAPI.ApiTokenDelete(context.Background(), tokenid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TokensAPIService ApiTokenGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tokenid string

		resp, httpRes, err := apiClient.TokensAPI.ApiTokenGet(context.Background(), tokenid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TokensAPIService ApiTokenList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var user string

		resp, httpRes, err := apiClient.TokensAPI.ApiTokenList(context.Background(), user).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TokensAPIService ApiTokenRemoveExpired", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var user string

		resp, httpRes, err := apiClient.TokensAPI.ApiTokenRemoveExpired(context.Background(), user).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
